// AUTO-GENERATED from locator_map.json — do not hand-edit.
// To fix a locator: edit locator_map.json (or rerun discovery), then regenerate this file.
import { Page, Locator } from '@playwright/test';
import { LocatorManager } from '../../../_shared/runtime/LocatorManager';

export class HomepagePage {
  constructor(private readonly page: Page) {}

  get _1(): Locator { return LocatorManager.resolve(this.page, "1"); }
  get a_loc_0106(): Locator { return LocatorManager.resolve(this.page, "a_loc_0106"); }
  get a_loc_0109(): Locator { return LocatorManager.resolve(this.page, "a_loc_0109"); }
  get a_loc_0121(): Locator { return LocatorManager.resolve(this.page, "a_loc_0121"); }
  get accept(): Locator { return LocatorManager.resolve(this.page, "accept"); }
  get advertising_and_marketing_turn_data_into_customer(): Locator { return LocatorManager.resolve(this.page, "advertising_and_marketing_turn_data_into_customer"); }
  get africa(): Locator { return LocatorManager.resolve(this.page, "africa"); }
  get agentic_ai_data_leaders_use_agentic_ai_to_lead(): Locator { return LocatorManager.resolve(this.page, "agentic_ai_data_leaders_use_agentic_ai_to_lead"); }
  get allow_advertising_category_allowed(): Locator { return LocatorManager.resolve(this.page, "allow_advertising_category_allowed"); }
  get allow_cross_context_behavioral_ads(): Locator { return LocatorManager.resolve(this.page, "allow_cross_context_behavioral_ads"); }
  get allow_functional_category_allowed(): Locator { return LocatorManager.resolve(this.page, "allow_functional_category_allowed"); }
  get allow_performance_category_allowed(): Locator { return LocatorManager.resolve(this.page, "allow_performance_category_allowed"); }
  get analyst_reports(): Locator { return LocatorManager.resolve(this.page, "analyst_reports"); }
  get architecture_center(): Locator { return LocatorManager.resolve(this.page, "architecture_center"); }
  get asia_pacific(): Locator { return LocatorManager.resolve(this.page, "asia_pacific"); }
  get australia_and_new_zealand(): Locator { return LocatorManager.resolve(this.page, "australia_and_new_zealand"); }
  get automotive_how_audi_uses_ai_to_connect_over_50(): Locator { return LocatorManager.resolve(this.page, "automotive_how_audi_uses_ai_to_connect_over_50"); }
  get aws_accessibility(): Locator { return LocatorManager.resolve(this.page, "aws_accessibility"); }
  get aws_cloud_security(): Locator { return LocatorManager.resolve(this.page, "aws_cloud_security"); }
  get aws_cookie_notice(): Locator { return LocatorManager.resolve(this.page, "aws_cookie_notice"); }
  get aws_govcloud_us_east(): Locator { return LocatorManager.resolve(this.page, "aws_govcloud_us_east"); }
  get aws_govcloud_us_west(): Locator { return LocatorManager.resolve(this.page, "aws_govcloud_us_west"); }
  get aws_marketplace(): Locator { return LocatorManager.resolve(this.page, "aws_marketplace"); }
  get aws_partners(): Locator { return LocatorManager.resolve(this.page, "aws_partners"); }
  get aws_privacy_notice(): Locator { return LocatorManager.resolve(this.page, "aws_privacy_notice"); }
  get aws_profile(): Locator { return LocatorManager.resolve(this.page, "aws_profile"); }
  get aws_profile_2(): Locator { return LocatorManager.resolve(this.page, "aws_profile_2"); }
  get aws_re_post(): Locator { return LocatorManager.resolve(this.page, "aws_re_post"); }
  get aws_solutions_library(): Locator { return LocatorManager.resolve(this.page, "aws_solutions_library"); }
  get aws_support_overview(): Locator { return LocatorManager.resolve(this.page, "aws_support_overview"); }
  get aws_trust_center(): Locator { return LocatorManager.resolve(this.page, "aws_trust_center"); }
  get back_to_top(): Locator { return LocatorManager.resolve(this.page, "back_to_top"); }
  get blogs(): Locator { return LocatorManager.resolve(this.page, "blogs"); }
  get builder_center(): Locator { return LocatorManager.resolve(this.page, "builder_center"); }
  get button_loc_0018(): Locator { return LocatorManager.resolve(this.page, "button_loc_0018"); }
  get button_loc_0030(): Locator { return LocatorManager.resolve(this.page, "button_loc_0030"); }
  get button_loc_0042(): Locator { return LocatorManager.resolve(this.page, "button_loc_0042"); }
  get button_loc_0043(): Locator { return LocatorManager.resolve(this.page, "button_loc_0043"); }
  get button_loc_0044(): Locator { return LocatorManager.resolve(this.page, "button_loc_0044"); }
  get button_loc_0045(): Locator { return LocatorManager.resolve(this.page, "button_loc_0045"); }
  get button_loc_0046(): Locator { return LocatorManager.resolve(this.page, "button_loc_0046"); }
  get button_loc_0047(): Locator { return LocatorManager.resolve(this.page, "button_loc_0047"); }
  get button_loc_0048(): Locator { return LocatorManager.resolve(this.page, "button_loc_0048"); }
  get button_loc_0049(): Locator { return LocatorManager.resolve(this.page, "button_loc_0049"); }
  get button_loc_0050(): Locator { return LocatorManager.resolve(this.page, "button_loc_0050"); }
  get button_loc_0051(): Locator { return LocatorManager.resolve(this.page, "button_loc_0051"); }
  get button_loc_0052(): Locator { return LocatorManager.resolve(this.page, "button_loc_0052"); }
  get button_loc_0053(): Locator { return LocatorManager.resolve(this.page, "button_loc_0053"); }
  get button_loc_0054(): Locator { return LocatorManager.resolve(this.page, "button_loc_0054"); }
  get button_loc_0055(): Locator { return LocatorManager.resolve(this.page, "button_loc_0055"); }
  get button_loc_0056(): Locator { return LocatorManager.resolve(this.page, "button_loc_0056"); }
  get button_loc_0057(): Locator { return LocatorManager.resolve(this.page, "button_loc_0057"); }
  get button_loc_0058(): Locator { return LocatorManager.resolve(this.page, "button_loc_0058"); }
  get button_loc_0059(): Locator { return LocatorManager.resolve(this.page, "button_loc_0059"); }
  get button_loc_0060(): Locator { return LocatorManager.resolve(this.page, "button_loc_0060"); }
  get button_loc_0061(): Locator { return LocatorManager.resolve(this.page, "button_loc_0061"); }
  get button_loc_0062(): Locator { return LocatorManager.resolve(this.page, "button_loc_0062"); }
  get button_loc_0063(): Locator { return LocatorManager.resolve(this.page, "button_loc_0063"); }
  get button_loc_0064(): Locator { return LocatorManager.resolve(this.page, "button_loc_0064"); }
  get button_loc_0065(): Locator { return LocatorManager.resolve(this.page, "button_loc_0065"); }
  get button_loc_0066(): Locator { return LocatorManager.resolve(this.page, "button_loc_0066"); }
  get button_loc_0067(): Locator { return LocatorManager.resolve(this.page, "button_loc_0067"); }
  get button_loc_0068(): Locator { return LocatorManager.resolve(this.page, "button_loc_0068"); }
  get button_loc_0069(): Locator { return LocatorManager.resolve(this.page, "button_loc_0069"); }
  get button_loc_0070(): Locator { return LocatorManager.resolve(this.page, "button_loc_0070"); }
  get button_loc_0071(): Locator { return LocatorManager.resolve(this.page, "button_loc_0071"); }
  get button_loc_0072(): Locator { return LocatorManager.resolve(this.page, "button_loc_0072"); }
  get button_loc_0073(): Locator { return LocatorManager.resolve(this.page, "button_loc_0073"); }
  get button_loc_0074(): Locator { return LocatorManager.resolve(this.page, "button_loc_0074"); }
  get button_loc_0075(): Locator { return LocatorManager.resolve(this.page, "button_loc_0075"); }
  get button_loc_0076(): Locator { return LocatorManager.resolve(this.page, "button_loc_0076"); }
  get button_loc_0077(): Locator { return LocatorManager.resolve(this.page, "button_loc_0077"); }
  get button_loc_0078(): Locator { return LocatorManager.resolve(this.page, "button_loc_0078"); }
  get button_loc_0079(): Locator { return LocatorManager.resolve(this.page, "button_loc_0079"); }
  get button_loc_0080(): Locator { return LocatorManager.resolve(this.page, "button_loc_0080"); }
  get button_loc_0081(): Locator { return LocatorManager.resolve(this.page, "button_loc_0081"); }
  get button_loc_0082(): Locator { return LocatorManager.resolve(this.page, "button_loc_0082"); }
  get canada_central(): Locator { return LocatorManager.resolve(this.page, "canada_central"); }
  get canada_west_calgary(): Locator { return LocatorManager.resolve(this.page, "canada_west_calgary"); }
  get cancel(): Locator { return LocatorManager.resolve(this.page, "cancel"); }
  get cancel_2(): Locator { return LocatorManager.resolve(this.page, "cancel_2"); }
  get close(): Locator { return LocatorManager.resolve(this.page, "close"); }
  get close_2(): Locator { return LocatorManager.resolve(this.page, "close_2"); }
  get close_notification(): Locator { return LocatorManager.resolve(this.page, "close_notification"); }
  get cloud_computing_concepts_hub(): Locator { return LocatorManager.resolve(this.page, "cloud_computing_concepts_hub"); }
  get contact_us(): Locator { return LocatorManager.resolve(this.page, "contact_us"); }
  get contact_us_2(): Locator { return LocatorManager.resolve(this.page, "contact_us_2"); }
  get cookie_notice(): Locator { return LocatorManager.resolve(this.page, "cookie_notice"); }
  get cookie_preferences(): Locator { return LocatorManager.resolve(this.page, "cookie_preferences"); }
  get create_account(): Locator { return LocatorManager.resolve(this.page, "create_account"); }
  get create_an_aws_account(): Locator { return LocatorManager.resolve(this.page, "create_an_aws_account"); }
  get customize(): Locator { return LocatorManager.resolve(this.page, "customize"); }
  get decline(): Locator { return LocatorManager.resolve(this.page, "decline"); }
  get discover_aws(): Locator { return LocatorManager.resolve(this.page, "discover_aws"); }
  get edge_locations_31(): Locator { return LocatorManager.resolve(this.page, "edge_locations_31"); }
  get email(): Locator { return LocatorManager.resolve(this.page, "email"); }
  get english(): Locator { return LocatorManager.resolve(this.page, "english"); }
  get english_2(): Locator { return LocatorManager.resolve(this.page, "english_2"); }
  get europe(): Locator { return LocatorManager.resolve(this.page, "europe"); }
  get event_code_of_conduct(): Locator { return LocatorManager.resolve(this.page, "event_code_of_conduct"); }
  get event_re_invent_2026_build_what_s_next_join_us(): Locator { return LocatorManager.resolve(this.page, "event_re_invent_2026_build_what_s_next_join_us"); }
  get event_terms_conditions(): Locator { return LocatorManager.resolve(this.page, "event_terms_conditions"); }
  get explore_aws_for_your_industry(): Locator { return LocatorManager.resolve(this.page, "explore_aws_for_your_industry"); }
  get facebook(): Locator { return LocatorManager.resolve(this.page, "facebook"); }
  get file_a_support_ticket(): Locator { return LocatorManager.resolve(this.page, "file_a_support_ticket"); }
  get filter_all(): Locator { return LocatorManager.resolve(this.page, "filter_all"); }
  get financial_services_develop_innovative_and_secure(): Locator { return LocatorManager.resolve(this.page, "financial_services_develop_innovative_and_secure"); }
  get games_enable_game_development_for_every_genre_and(): Locator { return LocatorManager.resolve(this.page, "games_enable_game_development_for_every_genre_and"); }
  get geographic_regions_9(): Locator { return LocatorManager.resolve(this.page, "geographic_regions_9"); }
  get getting_started(): Locator { return LocatorManager.resolve(this.page, "getting_started"); }
  get government_solutions_designed_to_help_government(): Locator { return LocatorManager.resolve(this.page, "government_solutions_designed_to_help_government"); }
  get healthcare_and_life_sciences_accelerate(): Locator { return LocatorManager.resolve(this.page, "healthcare_and_life_sciences_accelerate"); }
  get here(): Locator { return LocatorManager.resolve(this.page, "here"); }
  get hi_i_can_connect_you_with_an_aws_representative(): Locator { return LocatorManager.resolve(this.page, "hi_i_can_connect_you_with_an_aws_representative"); }
  get input_loc_0006(): Locator { return LocatorManager.resolve(this.page, "input_loc_0006"); }
  get input_loc_0007(): Locator { return LocatorManager.resolve(this.page, "input_loc_0007"); }
  get input_loc_0008(): Locator { return LocatorManager.resolve(this.page, "input_loc_0008"); }
  get instagram(): Locator { return LocatorManager.resolve(this.page, "instagram"); }
  get java_on_aws(): Locator { return LocatorManager.resolve(this.page, "java_on_aws"); }
  get javascript_on_aws(): Locator { return LocatorManager.resolve(this.page, "javascript_on_aws"); }
  get knowledge_center(): Locator { return LocatorManager.resolve(this.page, "knowledge_center"); }
  get legal(): Locator { return LocatorManager.resolve(this.page, "legal"); }
  get linkedin(): Locator { return LocatorManager.resolve(this.page, "linkedin"); }
  get media_and_entertainment_transform_media(): Locator { return LocatorManager.resolve(this.page, "media_and_entertainment_transform_media"); }
  get mexico_central(): Locator { return LocatorManager.resolve(this.page, "mexico_central"); }
  get middle_east(): Locator { return LocatorManager.resolve(this.page, "middle_east"); }
  get my_account(): Locator { return LocatorManager.resolve(this.page, "my_account"); }
  get navigate_products(): Locator { return LocatorManager.resolve(this.page, "navigate_products"); }
  get navigate_products_2(): Locator { return LocatorManager.resolve(this.page, "navigate_products_2"); }
  get navigate_products_3(): Locator { return LocatorManager.resolve(this.page, "navigate_products_3"); }
  get navigate_products_4(): Locator { return LocatorManager.resolve(this.page, "navigate_products_4"); }
  get net_on_aws(): Locator { return LocatorManager.resolve(this.page, "net_on_aws"); }
  get next_slide(): Locator { return LocatorManager.resolve(this.page, "next_slide"); }
  get no(): Locator { return LocatorManager.resolve(this.page, "no"); }
  get north_america(): Locator { return LocatorManager.resolve(this.page, "north_america"); }
  get open_feedback(): Locator { return LocatorManager.resolve(this.page, "open_feedback"); }
  get open_navigation_menu(): Locator { return LocatorManager.resolve(this.page, "open_navigation_menu"); }
  get opt_out_of_cross_context_behavioral_ads(): Locator { return LocatorManager.resolve(this.page, "opt_out_of_cross_context_behavioral_ads"); }
  get php_on_aws(): Locator { return LocatorManager.resolve(this.page, "php_on_aws"); }
  get podcasts(): Locator { return LocatorManager.resolve(this.page, "podcasts"); }
  get press_releases(): Locator { return LocatorManager.resolve(this.page, "press_releases"); }
  get previous_slide(): Locator { return LocatorManager.resolve(this.page, "previous_slide"); }
  get pricing(): Locator { return LocatorManager.resolve(this.page, "pricing"); }
  get privacy(): Locator { return LocatorManager.resolve(this.page, "privacy"); }
  get python_on_aws(): Locator { return LocatorManager.resolve(this.page, "python_on_aws"); }
  get re_invent(): Locator { return LocatorManager.resolve(this.page, "re_invent"); }
  get resources(): Locator { return LocatorManager.resolve(this.page, "resources"); }
  get retail(): Locator { return LocatorManager.resolve(this.page, "retail"); }
  get retail_adidas_drives_enterprise_wide(): Locator { return LocatorManager.resolve(this.page, "retail_adidas_drives_enterprise_wide"); }
  get retail_tapestry_amplifies_store_associate_voices(): Locator { return LocatorManager.resolve(this.page, "retail_tapestry_amplifies_store_associate_voices"); }
  get save_preferences(): Locator { return LocatorManager.resolve(this.page, "save_preferences"); }
  get save_preferences_2(): Locator { return LocatorManager.resolve(this.page, "save_preferences_2"); }
  get sdks_tools(): Locator { return LocatorManager.resolve(this.page, "sdks_tools"); }
  get search(): Locator { return LocatorManager.resolve(this.page, "search"); }
  get search_2(): Locator { return LocatorManager.resolve(this.page, "search_2"); }
  get show_8_more(): Locator { return LocatorManager.resolve(this.page, "show_8_more"); }
  get sign_in_to_console(): Locator { return LocatorManager.resolve(this.page, "sign_in_to_console"); }
  get site_terms(): Locator { return LocatorManager.resolve(this.page, "site_terms"); }
  get skip_to_main_content(): Locator { return LocatorManager.resolve(this.page, "skip_to_main_content"); }
  get solutions(): Locator { return LocatorManager.resolve(this.page, "solutions"); }
  get south_america(): Locator { return LocatorManager.resolve(this.page, "south_america"); }
  get start_free_with_aws(): Locator { return LocatorManager.resolve(this.page, "start_free_with_aws"); }
  get support(): Locator { return LocatorManager.resolve(this.page, "support"); }
  get telecommunications_accelerate_innovation_scale(): Locator { return LocatorManager.resolve(this.page, "telecommunications_accelerate_innovation_scale"); }
  get training(): Locator { return LocatorManager.resolve(this.page, "training"); }
  get travel_hospitality_how_booking_com_personalizes(): Locator { return LocatorManager.resolve(this.page, "travel_hospitality_how_booking_com_personalizes"); }
  get travel_hospitality_how_tui_uses_amazon_connect_to(): Locator { return LocatorManager.resolve(this.page, "travel_hospitality_how_tui_uses_amazon_connect_to"); }
  get twitch(): Locator { return LocatorManager.resolve(this.page, "twitch"); }
  get us_east_northern_virginia(): Locator { return LocatorManager.resolve(this.page, "us_east_northern_virginia"); }
  get us_east_ohio(): Locator { return LocatorManager.resolve(this.page, "us_east_ohio"); }
  get us_west_northern_california(): Locator { return LocatorManager.resolve(this.page, "us_west_northern_california"); }
  get us_west_oregon(): Locator { return LocatorManager.resolve(this.page, "us_west_oregon"); }
  get view_more_stories(): Locator { return LocatorManager.resolve(this.page, "view_more_stories"); }
  get what_is_agentic_ai(): Locator { return LocatorManager.resolve(this.page, "what_is_agentic_ai"); }
  get what_is_aws(): Locator { return LocatorManager.resolve(this.page, "what_is_aws"); }
  get what_is_cloud_computing(): Locator { return LocatorManager.resolve(this.page, "what_is_cloud_computing"); }
  get what_s_new(): Locator { return LocatorManager.resolve(this.page, "what_s_new"); }
  get x(): Locator { return LocatorManager.resolve(this.page, "x"); }
  get yes(): Locator { return LocatorManager.resolve(this.page, "yes"); }
  get youtube(): Locator { return LocatorManager.resolve(this.page, "youtube"); }
}

export const PAGE_REGISTRY: Record<string, new (page: Page) => Record<string, unknown>> = {
  "M01": HomepagePage,
};
