"""
synthesize_brd.py — generate a markdown BRD from DOM scan data.

Used in URL-only mode so ComprehensionAgent has *something* to parse.
The document describes the page's structure: inputs, buttons, navigation.
ComprehensionAgent then derives BusinessScenarios from it like any BRD.
"""

import os
from typing import Any, Dict, List, Optional


def synthesize_brd_from_dom(
    dom_intents: List[Dict[str, Any]],
    url: str,
    application_name: str,
    output_dir: str,
    user_flows: Optional[List[Dict[str, Any]]] = None,
) -> str:
    """
    Build a markdown requirements document from *dom_intents* and save it
    to *output_dir*/synthetic_brd.md.

    Returns the path to the written file.
    """
    os.makedirs(output_dir, exist_ok=True)

    fills = [i for i in dom_intents if i.get("action") == "fill"]
    clicks = [i for i in dom_intents if i.get("action") == "click"]
    selects = [i for i in dom_intents if i.get("action") == "select"]
    navigates = [i for i in dom_intents if i.get("action") == "navigate"]

    lines = [
        f"# Synthesized Requirements — {application_name}",
        "",
        f"**Source URL:** {url}",
        "**Generated by:** DiscoveryAgent (DOM scan)",
        "",
        "## Overview",
        f"This document was auto-generated by scanning the live page at `{url}`.",
        "It captures all interactive elements and infers testable workflows.",
        "",
    ]

    if fills:
        lines += ["## Input Fields (fill actions)", ""]
        for i in fills:
            name = i.get("intent_name", "")
            loc = i.get("locator_id", "")
            lines.append(f"- **{name}** — selector: `{loc}`")
        lines.append("")

    if selects:
        lines += ["## Dropdown / Select Fields", ""]
        for i in selects:
            name = i.get("intent_name", "")
            loc = i.get("locator_id", "")
            lines.append(f"- **{name}** — selector: `{loc}`")
        lines.append("")

    if clicks:
        lines += ["## Clickable Elements (buttons, links)", ""]
        for i in clicks:
            name = i.get("intent_name", "")
            loc = i.get("locator_id", "")
            lines.append(f"- **{name}** — selector: `{loc}`")
        lines.append("")

    if navigates:
        lines += ["## Navigation", ""]
        for i in navigates:
            lines.append(f"- {i.get('intent_name', '')}")
        lines.append("")

    lines += [
        "## Inferred User Workflows",
        "",
        "Based on the elements above, the following workflows are likely:",
        "",
    ]

    if fills and clicks:
        field_names = ", ".join(i["intent_name"] for i in fills[:4])
        submit_btn = next((i["intent_name"] for i in clicks if "submit" in i.get("intent_name","") or "login" in i.get("intent_name","") or "sign" in i.get("intent_name","") or "search" in i.get("intent_name","")), clicks[0]["intent_name"] if clicks else "submit")
        lines.append(f"1. User fills in {field_names} and clicks {submit_btn}.")

    if selects:
        sel_names = ", ".join(i["intent_name"] for i in selects[:2])
        lines.append(f"2. User selects options for {sel_names}.")

    if len(clicks) > 1:
        lines.append(f"3. User navigates the page using available action buttons.")

    lines.append("")

    # ── Observed user flows (interactive scan only) ──────────────────
    if user_flows:
        lines += ["## Observed User Flows (Recorded Interactions)", ""]
        lines.append(
            "The following flows were recorded during a live user session. "
            "Each flow represents a sequence of real user interactions and "
            "should be treated as high-confidence test scenarios."
        )
        lines.append("")
        for i, flow in enumerate(user_flows, start=1):
            name = flow.get("inferred_name", f"Flow {i}")
            stype = flow.get("inferred_scenario_type", "general")
            steps = flow.get("steps", [])
            api_calls = flow.get("api_calls_observed", [])

            lines.append(f"### Flow {i}: {name} (type: {stype})")
            lines.append("")
            lines.append("Steps:")
            for step in steps:
                text = step.get("display_text") or step.get("locator_id") or "element"
                action = step.get("action", "click")
                path = step.get("page_path", "")
                step_desc = f"  {step.get('step', '?')}. {action.capitalize()} '{text}'"
                if path:
                    step_desc += f" (on {path})"
                lines.append(step_desc)
            if api_calls:
                lines.append("API calls observed during this flow:")
                for call in api_calls:
                    lines.append(f"  - {call.get('method', 'GET')} {call.get('url', '')}")
            lines.append("")

    content = "\n".join(lines)
    path = os.path.join(output_dir, "synthetic_brd.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

    return path
