"""
AgentTestGenerationAgent — BRD-grounded runtime tests the live application can actually run.

Runs after Runtime Discovery and App Classification, so tests are designed for the app that exists:
  * the model sees the discovered surface (app type, pages, forms with their field labels, buttons, chat box,
    downloads) and writes each test in the app's own interaction model (form values, chat message, page visit,
    export) — not "one chat message" for a form app;
  * only acceptance criteria verifiable at runtime (criterion/requirement verifiability runtime|both) get tests;
    performance, fault-injection, infrastructure and other non-observable claims are left to code review and listed
    as `static_only_criteria` instead of becoming tests that can never run;
  * the number of tests is sized to the execution budget for the app class (EXECUTION_BUDGET): one positive test
    per runtime criterion first (by requirement priority), then negative/edge tests where the BRD describes them;
    criteria beyond the budget are listed too, with that reason;
  * no runtime tests at all when nothing can run them (BRD-only mode, no live URL, the live app could not be
    inspected, or it is behind a login without a working test account) — the criteria are judged from the code and
    the reason is reported, rather than generating tests that end up "Not executed".

Two families, generated by two parallel schema-enforced Gemini calls:
  * agent_specific — tests per BRD requirement, each verifying one of its acceptance criteria
  * general        — cross-cutting qualities the BRD states that are observable through the app (validation
                     messages, out-of-scope handling, error messages); none if the BRD states none

Grounding: every test must quote the BRD; normalize_tests() machine-checks that quote against the BRD text (not
against MTA's own paraphrases), discards tests that can't be traced or can't be pinned to a criterion of their
requirement, and drops tests the model itself marked as static.
"""

import json
from concurrent.futures import ThreadPoolExecutor
from difflib import SequenceMatcher
from typing import Any, Dict, List, Optional, Tuple

from agents.base_agent import BaseAgent
from agents.test_creation.agent_test_generation.prompt import (
    AGENT_SPECIFIC_INSTRUCTIONS,
    GENERAL_INSTRUCTIONS,
    TEST_GENERATION_PROMPT,
)
from agents.test_creation.agent_test_generation.skills import SKILLS
from agents.test_creation.agent_test_generation.tools import TEST_CASES, BrdIndex, generate_json
from connectors.connector_registry import ConnectorRegistry
from engines.runtime.actions import build_inventory
from tools.shared import get_logger

MAX_BRD_CHARS_IN_PROMPT = 80_000
MAX_SURFACE_CHARS = 14_000
# Runtime tests per run by app class: what the executor finishes in roughly 30-60 minutes (measured: a document
# generator needs ~3 min per test on the app's side; chat/form/API tests ~20-60 s).
EXECUTION_BUDGET = {"Document Generator": 20, "Workflow System": 24, "Form Application": 30, "Hybrid Application": 30,
                    "Chatbot": 40, "REST API": 40, "Dashboard": 20, "Static Website": 10}
DEFAULT_BUDGET = 24
GENERAL_MAX = 6
MIN_CRITERION_MATCH = 0.35
_VARIANTS = {"positive", "negative", "edge", "security", "robustness", "out_of_scope", "hallucination", "ambiguity"}
_PRIORITIES = {"high", "medium", "low"}
_PRIORITY_RANK = {"high": 0, "medium": 1, "low": 2}
_RUNTIME = {"runtime", "both"}
_FALLBACK_CLASSES = {"Chatbot", "REST API"}  # reachable through live_agent_execution without a browser profile


class AgentTestGenerationAgent(BaseAgent):
    MODULE_NAME = "agent_test_generation"

    def __init__(self, settings: Optional[dict] = None):
        self.settings = settings or {}
        self._registry = ConnectorRegistry(self.settings)
        self.logger = get_logger("agent.agent_test_generation")

    def execute(self, request: dict, state: dict) -> Dict[str, Any]:
        emit = request.get("emit") or (lambda *a, **k: None)
        requirements: List[dict] = request.get("requirements") or []
        brd_text: str = request.get("brd_markdown") or ""
        if not requirements:
            return {"module": self.MODULE_NAME, "status": "failed", "error": "No requirements to generate tests from."}

        runtime_criteria, static_only = runtime_targets(requirements)
        blocked = why_not_runnable(request)
        if blocked:
            reason = f"No runtime tests: {blocked}. All {len(runtime_criteria) + len(static_only)} acceptance criteria " \
                     "are judged from the code."
            emit(reason, "warning")
            static_all = static_only + [{**c, "reason": blocked} for c in runtime_criteria]
            return {"module": self.MODULE_NAME, "status": "skipped", "reason": reason, "test_cases": [],
                    "static_only_criteria": static_all}
        if not runtime_criteria:
            reason = "No acceptance criterion is verifiable through the running app; all are judged from the code."
            emit(reason, "warning")
            return {"module": self.MODULE_NAME, "status": "skipped", "reason": reason, "test_cases": [],
                    "static_only_criteria": static_only}

        app_type = _app_type(request)
        budget = int((self.settings.get("execution") or {}).get("max_runtime_tests")
                     or EXECUTION_BUDGET.get(app_type, DEFAULT_BUDGET))
        chosen, over_budget = _within_budget(runtime_criteria, budget)
        static_only += [{**c, "reason": f"over the runtime test budget ({budget} tests for a {app_type})"}
                        for c in over_budget]
        chosen_codes = {c["code"] for c in chosen}
        general_count = max(0, min(GENERAL_MAX, budget - len(chosen)))

        base = dict(
            skill_header=SKILLS["agent_test_design"].header(),
            interface=_describe_interface(request.get("agent_profile") or {}, request.get("mode")),
            app_surface=describe_surface(request.get("runtime_profile"), app_type),
            execution_budget=(f"at most {budget} runtime tests in total; one positive test per listed criterion comes "
                              f"first, then negative/edge tests only where the BRD describes that handling"),
            requirements=json.dumps([{**{k: r.get(k) for k in (
                "code", "title", "description", "priority", "kind", "verifiability", "section", "source_quote")},
                "criteria": [{"code": c["code"], "statement": c["statement"], "oracle_hint": c.get("oracle_hint"),
                              "verifiability": _criterion_verifiability(c, r)}
                             for c in (r.get("criteria") or []) if c["code"] in chosen_codes]}
                for r in requirements if any(c["code"] in chosen_codes for c in r.get("criteria") or [])],
                indent=1, ensure_ascii=False),
            brd_text=brd_text[:MAX_BRD_CHARS_IN_PROMPT] or "(BRD text unavailable — use the requirements above)",
        )
        prompts = {"agent_specific": TEST_GENERATION_PROMPT.substitute(**base, family_instructions=AGENT_SPECIFIC_INSTRUCTIONS.substitute(
            per_requirement_rule=(f"one positive test for each of the {len(chosen)} criteria listed, then negative or "
                                  "edge tests where the BRD describes rejection, validation or a boundary"),
            max_tests=budget - general_count))}
        if general_count:
            prompts["general"] = TEST_GENERATION_PROMPT.substitute(**base, family_instructions=GENERAL_INSTRUCTIONS.substitute(
                count=general_count))
        emit(f"Generating up to {budget} runtime tests for {len(chosen)} runtime-verifiable criteria on a {app_type}"
             + (f"; {len(static_only)} criteria are left to code review" if static_only else "") + ".")
        llm = self._registry.get_llm(request.get("connector_mode"))

        def ask(family: str) -> List[Any]:
            return generate_json(llm, prompts[family], required_keys=["test_cases"], schema=TEST_CASES).get("test_cases") or []

        raw: List[Any] = []
        errors: List[str] = []
        with ThreadPoolExecutor(max_workers=len(prompts)) as pool:
            futures = {family: pool.submit(ask, family) for family in prompts}
            for family, fut in futures.items():
                try:
                    items = fut.result()
                    for item in items:
                        if isinstance(item, dict):
                            item["category"] = family
                    raw.extend(items)
                except Exception as exc:
                    errors.append(f"{family}: {exc}")
                    emit(f"Generating {family.replace('_', '-')} tests failed: {exc}", "warning")
        if errors and not raw:
            return {"module": self.MODULE_NAME, "status": "failed", "error": "Test generation failed — " + "; ".join(errors),
                    "static_only_criteria": static_only}

        tests, dropped = normalize_tests(raw, requirements, brd_text, allowed_criteria=chosen_codes, budget=budget)
        for why, n in dropped.items():
            if n:
                emit(f"Discarded {n} generated test(s): {why}.", "warning")
        if not tests:
            return {"module": self.MODULE_NAME, "status": "failed",
                    "error": "None of the generated tests could be traced to the BRD and a runtime criterion.",
                    "static_only_criteria": static_only}

        covered = {t["criterion_code"] for t in tests}
        missed = [c for c in chosen if c["code"] not in covered]
        emit(f"Generated {len(tests)} runtime tests covering {len(covered)}/{len(chosen)} runtime criteria.", "success")
        if missed:
            emit(f"Runtime criteria without a test: {', '.join(c['code'] for c in missed[:20])}", "warning")
        result = {"module": self.MODULE_NAME, "status": "partial" if errors else "success", "test_cases": tests,
                  "static_only_criteria": static_only + [{**c, "reason": "no executable test could be designed"}
                                                         for c in missed]}
        if errors:
            result["error"] = "; ".join(errors)
        return result


# ── what can run, and what to test ──────────────────────────────────────────

def why_not_runnable(request: dict) -> Optional[str]:
    """None when runtime tests can execute; otherwise the reason (shown to the user)."""
    if request.get("mode") == "brd_only" or not (request.get("live_url") or "").strip():
        return "the app is not deployed (BRD-only review)"
    profile = request.get("runtime_profile")
    fallback_ok = _app_type(request) in _FALLBACK_CLASSES
    if not profile:
        return None if fallback_ok else "the live app could not be inspected in a browser (see Runtime discovery)"
    login = profile.get("login") or {}
    if profile.get("needs_credentials"):
        if login.get("attempted") and not login.get("succeeded"):
            return f"logging in with the project's test account failed ({login.get('error')})"
        return "the live app is behind a login and the project has no test account"
    if profile.get("app_type") == "Unreachable":
        return "the live URL did not respond"
    if not (profile.get("pages") or []) and not fallback_ok:
        return "runtime discovery found no page to test"
    inv = build_inventory(profile)
    if not inv["elements"] and not fallback_ok and _app_type(request) not in ("Static Website", "Dashboard"):
        return "runtime discovery found nothing to act on (no forms, buttons or chat box)"
    unrendered = profile.get("unrendered_form_pages") or []
    if unrendered and not inv["forms"] and not inv["chat_boxes"] and not fallback_ok:
        return (f"the live app's input pages ({', '.join(unrendered[:4])}) never finished loading for MTA, so there was "
                "no form to test (the app's backend may have been starting up); re-run when the app responds")
    return None


def runtime_targets(requirements: List[dict]) -> Tuple[List[dict], List[dict]]:
    """(criteria verifiable through the running app, criteria left to code review) with requirement context."""
    runtime, static = [], []
    for r in requirements:
        for c in r.get("criteria") or []:
            row = {"code": c["code"], "requirement": r["code"], "priority": r.get("priority") or "medium",
                   "statement": c.get("statement")}
            if _criterion_verifiability(c, r) in _RUNTIME and c.get("oracle_hint") != "static":
                runtime.append(row)
            else:
                static.append({**row, "reason": "not observable through the running app (judged from the code)"})
    return runtime, static


def _criterion_verifiability(c: dict, r: dict) -> str:
    return str(c.get("verifiability") or r.get("verifiability") or "both").lower()


def _within_budget(criteria: List[dict], budget: int) -> Tuple[List[dict], List[dict]]:
    """Highest-priority criteria first; keep requirement order within a priority."""
    ranked = sorted(enumerate(criteria), key=lambda ic: (_PRIORITY_RANK.get(ic[1]["priority"], 1), ic[0]))
    chosen = [c for _, c in ranked[:budget]]
    keep = {c["code"] for c in chosen}
    return [c for c in criteria if c["code"] in keep], [c for c in criteria if c["code"] not in keep]


def _app_type(request: dict) -> str:
    return ((request.get("app_classification") or {}).get("app_type")
            or (request.get("runtime_profile") or {}).get("app_type") or "Unknown")


def describe_surface(profile: Optional[dict], app_type: str) -> str:
    """Compact, model-readable description of what the live app offers (from Runtime Discovery)."""
    if not profile:
        return f"App type: {app_type}. The live app was not inspected in a browser; tests reach it through its API/chat interface."
    inv = build_inventory(profile)
    els = inv["elements"]
    lines = [f"App type: {app_type}. Pages inspected: {profile.get('pages_inspected', 0)}."
             + (" Logged in with the project's test account." if (profile.get("login") or {}).get("succeeded") else "")]
    for p in inv["pages"]:
        lines.append(f"\nPage {p['path']}" + (f" — {p['title']}" if p.get("title") else "")
                     + (f" — headings: {'; '.join(p['headings'][:4])}" if p.get("headings") else ""))
        for f in inv["forms"].values():
            if f["page"] != p["path"]:
                continue
            lines.append(f"  Form (submit: {f.get('submit_text') or 'none'}):")
            for fid in f["fields"]:
                e = els[fid]
                extra = (" required" if e["required"] else "") + (f" options: {', '.join(e['options'][:8])}" if e.get("options") else "") \
                    + (" (list row)" if e.get("revealed_by") else "")
                lines.append(f"    - {e['label'] or e['name'] or '(unlabelled)'} [{e['type']}]{extra}")
        buttons = [e["text"] for e in els.values() if e["kind"] == "button" and e["page"] == p["path"]]
        if buttons:
            lines.append(f"  Buttons: {', '.join(sorted(set(buttons))[:25])}")
        if any(e["kind"] == "link" and e["page"] == p["path"] for e in els.values()):
            lines.append("  Download links present.")
    if inv["chat_boxes"]:
        lines.append("\nChat box present: tests can send a message and read the reply.")
    if profile.get("downloads"):
        lines.append("Downloads/exports are offered (some appear only after generating a result).")
    text = "\n".join(lines)
    return text if len(text) <= MAX_SURFACE_CHARS else text[:MAX_SURFACE_CHARS] + "\n… (truncated)"


def _describe_interface(profile: dict, mode: Optional[str]) -> str:
    """How messages reach the app's API/chat (from the code), when it has one."""
    iface = profile.get("interface") or {}
    lines = [f"Interface type (from the code): {iface.get('type') or 'unknown'} ({iface.get('framework') or 'unknown framework'})."]
    for ep in (iface.get("endpoints") or [])[:3]:
        if isinstance(ep, dict) and ep.get("path"):
            lines.append(f"- {ep.get('method', 'POST')} {ep['path']}: {ep.get('description') or ''} "
                         f"(the user's message goes in '{ep.get('input_field') or 'message'}')")
    if mode == "brd_only":
        lines.append("The app is not deployed yet.")
    return "\n".join(lines)


# ── normalisation ────────────────────────────────────────────────────────────

def _criterion_code(item: dict, req: Optional[dict]) -> Optional[str]:
    """The AC-xx.y a test verifies: the model's code if it belongs to the requirement, else a confident text match."""
    criteria = (req or {}).get("criteria") or []
    if not criteria:
        return None
    given = str(item.get("criterion_code") or "").strip().upper()
    if any(c["code"] == given for c in criteria):
        return given
    text = str(item.get("acceptance_criterion") or item.get("expected_behavior") or "").lower()
    best = max(criteria, key=lambda c: SequenceMatcher(None, text, c["statement"].lower()).ratio())
    return best["code"] if SequenceMatcher(None, text, best["statement"].lower()).ratio() >= MIN_CRITERION_MATCH else None


def normalize_tests(raw: List[Any], requirements: List[dict], brd_text: str,
                    allowed_criteria: Optional[set] = None, budget: int = 40) -> Tuple[List[Dict[str, Any]], Dict[str, int]]:
    """Validate/coerce LLM tests; keep only runtime tests traced to the BRD and pinned to an allowed criterion.

    Returns (tests, dropped counts by reason). Positive tests first so the budget always covers each criterion once.
    """
    brd_index = BrdIndex(brd_text) if brd_text else None
    by_code = {r["code"]: r for r in requirements}
    # without BRD text, a test may quote its requirement's verified source quote — never MTA's own paraphrases
    quote_index = {code: BrdIndex(r.get("source_quote") or "") for code, r in by_code.items()}
    dropped = {"not traceable to a BRD statement": 0, "not tied to a runtime acceptance criterion": 0,
               "only checkable from the code (static)": 0, "over the runtime test budget": 0}

    cleaned: List[Dict[str, Any]] = []
    for item in raw:
        if not isinstance(item, dict):
            continue
        message = str(item.get("input") or "").strip()
        title = str(item.get("title") or "").strip()
        if not message or not title:
            continue
        if str(item.get("execution") or "ui").lower() == "static":
            dropped["only checkable from the code (static)"] += 1
            continue
        ref = item.get("requirement_ref")
        ref = str(ref).strip().upper() if ref else None
        ref = ref if ref in by_code else None
        category = "agent_specific" if item.get("category") == "agent_specific" else "general"
        crit_code = _criterion_code(item, by_code.get(ref)) if ref else None
        if not ref or not crit_code or (allowed_criteria is not None and crit_code not in allowed_criteria):
            dropped["not tied to a runtime acceptance criterion"] += 1
            continue

        quote = str(item.get("brd_reference") or "").strip()
        traced = bool(brd_index and brd_index.grounded(quote)) or (not brd_index and quote_index[ref].grounded(quote))
        if not traced:
            dropped["not traceable to a BRD statement"] += 1
            continue

        variant = str(item.get("variant_type") or "positive").lower().replace(" ", "_")
        priority = str(item.get("priority") or by_code[ref].get("priority") or "medium").lower()
        criteria = item.get("pass_criteria") or []
        statement = next((c["statement"] for c in by_code[ref].get("criteria") or [] if c["code"] == crit_code), None)
        cleaned.append({
            "title": title[:300],
            "category": category,
            "variant_type": variant if variant in _VARIANTS else "positive",
            "priority": priority if priority in _PRIORITIES else "medium",
            "requirement_ref": ref,
            "criterion_code": crit_code,
            "acceptance_criterion": (statement or str(item.get("acceptance_criterion") or ""))[:1000] or None,
            "brd_reference": quote[:1000] or None,
            "area": str(item.get("area") or by_code[ref]["title"])[:80],
            "input": message[:8000],
            "execution": "api" if str(item.get("execution") or "").lower() == "api" else "ui",
            "expected_behavior": str(item.get("expected_behavior") or "").strip(),
            "pass_criteria": [str(c) for c in criteria if str(c).strip()][:6] if isinstance(criteria, list) else [],
        })

    # one positive per criterion first, then the rest, within the budget
    first, rest, seen = [], [], set()
    for t in cleaned:
        if t["variant_type"] == "positive" and t["criterion_code"] not in seen:
            seen.add(t["criterion_code"])
            first.append(t)
        else:
            rest.append(t)
    ordered = (first + rest)[:budget]
    dropped["over the runtime test budget"] = max(0, len(first) + len(rest) - len(ordered))
    ordered.sort(key=lambda t: (t["category"] != "agent_specific", t["requirement_ref"] or "", t["criterion_code"] or ""))
    for i, t in enumerate(ordered, 1):
        t["code"] = f"TC-{i:03d}"
        t["status"] = "pending"
    return ordered, dropped
