// AUTO-GENERATED from locator_map.json — do not hand-edit.
// To fix a locator: edit locator_map.json (or rerun discovery), then regenerate this file.
import { Page, Locator } from '@playwright/test';
import { LocatorManager } from '../../../_shared/runtime/LocatorManager';

export class HomepagePage {
  constructor(private readonly page: Page) {}

  get _1(): Locator { return LocatorManager.resolve(this.page, "1"); }
  get a_loc_0108(): Locator { return LocatorManager.resolve(this.page, "a_loc_0108"); }
  get a_loc_0111(): Locator { return LocatorManager.resolve(this.page, "a_loc_0111"); }
  get a_loc_0117(): Locator { return LocatorManager.resolve(this.page, "a_loc_0117"); }
  get a_loc_0118(): Locator { return LocatorManager.resolve(this.page, "a_loc_0118"); }
  get a_loc_0119(): Locator { return LocatorManager.resolve(this.page, "a_loc_0119"); }
  get a_loc_0120(): Locator { return LocatorManager.resolve(this.page, "a_loc_0120"); }
  get a_loc_0121(): Locator { return LocatorManager.resolve(this.page, "a_loc_0121"); }
  get a_loc_0122(): Locator { return LocatorManager.resolve(this.page, "a_loc_0122"); }
  get a_loc_0123(): Locator { return LocatorManager.resolve(this.page, "a_loc_0123"); }
  get a_loc_0123_2(): Locator { return LocatorManager.resolve(this.page, "a_loc_0123_2"); }
  get a_loc_0124(): Locator { return LocatorManager.resolve(this.page, "a_loc_0124"); }
  get a_loc_0169(): Locator { return LocatorManager.resolve(this.page, "a_loc_0169"); }
  get a_loc_0170(): Locator { return LocatorManager.resolve(this.page, "a_loc_0170"); }
  get a_loc_0171(): Locator { return LocatorManager.resolve(this.page, "a_loc_0171"); }
  get a_loc_0172(): Locator { return LocatorManager.resolve(this.page, "a_loc_0172"); }
  get a_loc_0173(): Locator { return LocatorManager.resolve(this.page, "a_loc_0173"); }
  get a_loc_0174(): Locator { return LocatorManager.resolve(this.page, "a_loc_0174"); }
  get a_loc_0175(): Locator { return LocatorManager.resolve(this.page, "a_loc_0175"); }
  get a_loc_0176(): Locator { return LocatorManager.resolve(this.page, "a_loc_0176"); }
  get accept(): Locator { return LocatorManager.resolve(this.page, "accept"); }
  get advertising_and_marketing_turn_data_into_customer(): Locator { return LocatorManager.resolve(this.page, "advertising_and_marketing_turn_data_into_customer"); }
  get advertising_marketing_pinterest_drives_visual(): Locator { return LocatorManager.resolve(this.page, "advertising_marketing_pinterest_drives_visual"); }
  get africa(): Locator { return LocatorManager.resolve(this.page, "africa"); }
  get agentic_ai_data_leaders_use_agentic_ai_to_lead(): Locator { return LocatorManager.resolve(this.page, "agentic_ai_data_leaders_use_agentic_ai_to_lead"); }
  get analyst_reports(): Locator { return LocatorManager.resolve(this.page, "analyst_reports"); }
  get architecture_center(): Locator { return LocatorManager.resolve(this.page, "architecture_center"); }
  get asia_pacific(): Locator { return LocatorManager.resolve(this.page, "asia_pacific"); }
  get australia_and_new_zealand(): Locator { return LocatorManager.resolve(this.page, "australia_and_new_zealand"); }
  get automotive_how_audi_uses_ai_to_connect_over_50(): Locator { return LocatorManager.resolve(this.page, "automotive_how_audi_uses_ai_to_connect_over_50"); }
  get automotive_toyota_reduces_call_handling_times_by(): Locator { return LocatorManager.resolve(this.page, "automotive_toyota_reduces_call_handling_times_by"); }
  get aws_accessibility(): Locator { return LocatorManager.resolve(this.page, "aws_accessibility"); }
  get aws_accessibility_3(): Locator { return LocatorManager.resolve(this.page, "aws_accessibility_3"); }
  get aws_cloud_security(): Locator { return LocatorManager.resolve(this.page, "aws_cloud_security"); }
  get aws_cookie_notice(): Locator { return LocatorManager.resolve(this.page, "aws_cookie_notice"); }
  get aws_govcloud_us_east(): Locator { return LocatorManager.resolve(this.page, "aws_govcloud_us_east"); }
  get aws_govcloud_us_west(): Locator { return LocatorManager.resolve(this.page, "aws_govcloud_us_west"); }
  get aws_marketplace(): Locator { return LocatorManager.resolve(this.page, "aws_marketplace"); }
  get aws_partners(): Locator { return LocatorManager.resolve(this.page, "aws_partners"); }
  get aws_privacy_notice(): Locator { return LocatorManager.resolve(this.page, "aws_privacy_notice"); }
  get aws_re_post(): Locator { return LocatorManager.resolve(this.page, "aws_re_post"); }
  get aws_re_post_3(): Locator { return LocatorManager.resolve(this.page, "aws_re_post_3"); }
  get aws_solutions_library(): Locator { return LocatorManager.resolve(this.page, "aws_solutions_library"); }
  get aws_support_overview(): Locator { return LocatorManager.resolve(this.page, "aws_support_overview"); }
  get aws_support_overview_3(): Locator { return LocatorManager.resolve(this.page, "aws_support_overview_3"); }
  get aws_trust_center(): Locator { return LocatorManager.resolve(this.page, "aws_trust_center"); }
  get back_to_top(): Locator { return LocatorManager.resolve(this.page, "back_to_top"); }
  get blogs(): Locator { return LocatorManager.resolve(this.page, "blogs"); }
  get builder_center(): Locator { return LocatorManager.resolve(this.page, "builder_center"); }
  get button_loc_0017(): Locator { return LocatorManager.resolve(this.page, "button_loc_0017"); }
  get button_loc_0018(): Locator { return LocatorManager.resolve(this.page, "button_loc_0018"); }
  get button_loc_0019(): Locator { return LocatorManager.resolve(this.page, "button_loc_0019"); }
  get button_loc_0021(): Locator { return LocatorManager.resolve(this.page, "button_loc_0021"); }
  get button_loc_0025(): Locator { return LocatorManager.resolve(this.page, "button_loc_0025"); }
  get button_loc_0031(): Locator { return LocatorManager.resolve(this.page, "button_loc_0031"); }
  get button_loc_0032(): Locator { return LocatorManager.resolve(this.page, "button_loc_0032"); }
  get button_loc_0033(): Locator { return LocatorManager.resolve(this.page, "button_loc_0033"); }
  get button_loc_0034(): Locator { return LocatorManager.resolve(this.page, "button_loc_0034"); }
  get button_loc_0035(): Locator { return LocatorManager.resolve(this.page, "button_loc_0035"); }
  get button_loc_0044(): Locator { return LocatorManager.resolve(this.page, "button_loc_0044"); }
  get button_loc_0045(): Locator { return LocatorManager.resolve(this.page, "button_loc_0045"); }
  get button_loc_0046(): Locator { return LocatorManager.resolve(this.page, "button_loc_0046"); }
  get button_loc_0047(): Locator { return LocatorManager.resolve(this.page, "button_loc_0047"); }
  get button_loc_0048(): Locator { return LocatorManager.resolve(this.page, "button_loc_0048"); }
  get button_loc_0049(): Locator { return LocatorManager.resolve(this.page, "button_loc_0049"); }
  get button_loc_0050(): Locator { return LocatorManager.resolve(this.page, "button_loc_0050"); }
  get button_loc_0051(): Locator { return LocatorManager.resolve(this.page, "button_loc_0051"); }
  get button_loc_0052(): Locator { return LocatorManager.resolve(this.page, "button_loc_0052"); }
  get button_loc_0053(): Locator { return LocatorManager.resolve(this.page, "button_loc_0053"); }
  get button_loc_0054(): Locator { return LocatorManager.resolve(this.page, "button_loc_0054"); }
  get button_loc_0055(): Locator { return LocatorManager.resolve(this.page, "button_loc_0055"); }
  get button_loc_0056(): Locator { return LocatorManager.resolve(this.page, "button_loc_0056"); }
  get button_loc_0057(): Locator { return LocatorManager.resolve(this.page, "button_loc_0057"); }
  get button_loc_0058(): Locator { return LocatorManager.resolve(this.page, "button_loc_0058"); }
  get button_loc_0059(): Locator { return LocatorManager.resolve(this.page, "button_loc_0059"); }
  get button_loc_0060(): Locator { return LocatorManager.resolve(this.page, "button_loc_0060"); }
  get button_loc_0061(): Locator { return LocatorManager.resolve(this.page, "button_loc_0061"); }
  get button_loc_0062(): Locator { return LocatorManager.resolve(this.page, "button_loc_0062"); }
  get button_loc_0063(): Locator { return LocatorManager.resolve(this.page, "button_loc_0063"); }
  get button_loc_0064(): Locator { return LocatorManager.resolve(this.page, "button_loc_0064"); }
  get button_loc_0065(): Locator { return LocatorManager.resolve(this.page, "button_loc_0065"); }
  get button_loc_0066(): Locator { return LocatorManager.resolve(this.page, "button_loc_0066"); }
  get button_loc_0067(): Locator { return LocatorManager.resolve(this.page, "button_loc_0067"); }
  get button_loc_0068(): Locator { return LocatorManager.resolve(this.page, "button_loc_0068"); }
  get button_loc_0069(): Locator { return LocatorManager.resolve(this.page, "button_loc_0069"); }
  get button_loc_0070(): Locator { return LocatorManager.resolve(this.page, "button_loc_0070"); }
  get button_loc_0071(): Locator { return LocatorManager.resolve(this.page, "button_loc_0071"); }
  get button_loc_0072(): Locator { return LocatorManager.resolve(this.page, "button_loc_0072"); }
  get button_loc_0073(): Locator { return LocatorManager.resolve(this.page, "button_loc_0073"); }
  get button_loc_0074(): Locator { return LocatorManager.resolve(this.page, "button_loc_0074"); }
  get button_loc_0075(): Locator { return LocatorManager.resolve(this.page, "button_loc_0075"); }
  get button_loc_0076(): Locator { return LocatorManager.resolve(this.page, "button_loc_0076"); }
  get button_loc_0077(): Locator { return LocatorManager.resolve(this.page, "button_loc_0077"); }
  get button_loc_0078(): Locator { return LocatorManager.resolve(this.page, "button_loc_0078"); }
  get button_loc_0079(): Locator { return LocatorManager.resolve(this.page, "button_loc_0079"); }
  get button_loc_0080(): Locator { return LocatorManager.resolve(this.page, "button_loc_0080"); }
  get button_loc_0081(): Locator { return LocatorManager.resolve(this.page, "button_loc_0081"); }
  get button_loc_0082(): Locator { return LocatorManager.resolve(this.page, "button_loc_0082"); }
  get button_loc_0083(): Locator { return LocatorManager.resolve(this.page, "button_loc_0083"); }
  get button_loc_0084(): Locator { return LocatorManager.resolve(this.page, "button_loc_0084"); }
  get button_loc_0101(): Locator { return LocatorManager.resolve(this.page, "button_loc_0101"); }
  get canada_central(): Locator { return LocatorManager.resolve(this.page, "canada_central"); }
  get canada_west_calgary(): Locator { return LocatorManager.resolve(this.page, "canada_west_calgary"); }
  get cancel(): Locator { return LocatorManager.resolve(this.page, "cancel"); }
  get cancel_2(): Locator { return LocatorManager.resolve(this.page, "cancel_2"); }
  get cloud_computing_concepts_hub(): Locator { return LocatorManager.resolve(this.page, "cloud_computing_concepts_hub"); }
  get contact_us(): Locator { return LocatorManager.resolve(this.page, "contact_us"); }
  get contact_us_2(): Locator { return LocatorManager.resolve(this.page, "contact_us_2"); }
  get contact_us_4(): Locator { return LocatorManager.resolve(this.page, "contact_us_4"); }
  get contact_us_5(): Locator { return LocatorManager.resolve(this.page, "contact_us_5"); }
  get cookie_notice(): Locator { return LocatorManager.resolve(this.page, "cookie_notice"); }
  get cookie_preferences(): Locator { return LocatorManager.resolve(this.page, "cookie_preferences"); }
  get cookie_preferences_3(): Locator { return LocatorManager.resolve(this.page, "cookie_preferences_3"); }
  get create_account(): Locator { return LocatorManager.resolve(this.page, "create_account"); }
  get create_an_aws_account(): Locator { return LocatorManager.resolve(this.page, "create_an_aws_account"); }
  get customize(): Locator { return LocatorManager.resolve(this.page, "customize"); }
  get decline(): Locator { return LocatorManager.resolve(this.page, "decline"); }
  get discover_aws(): Locator { return LocatorManager.resolve(this.page, "discover_aws"); }
  get edge_locations_31(): Locator { return LocatorManager.resolve(this.page, "edge_locations_31"); }
  get english(): Locator { return LocatorManager.resolve(this.page, "english"); }
  get english_2(): Locator { return LocatorManager.resolve(this.page, "english_2"); }
  get europe(): Locator { return LocatorManager.resolve(this.page, "europe"); }
  get event_code_of_conduct(): Locator { return LocatorManager.resolve(this.page, "event_code_of_conduct"); }
  get event_code_of_conduct_3(): Locator { return LocatorManager.resolve(this.page, "event_code_of_conduct_3"); }
  get event_re_invent_2026_build_what_s_next_join_us(): Locator { return LocatorManager.resolve(this.page, "event_re_invent_2026_build_what_s_next_join_us"); }
  get event_terms_conditions(): Locator { return LocatorManager.resolve(this.page, "event_terms_conditions"); }
  get event_terms_conditions_3(): Locator { return LocatorManager.resolve(this.page, "event_terms_conditions_3"); }
  get explore_aws_for_your_industry(): Locator { return LocatorManager.resolve(this.page, "explore_aws_for_your_industry"); }
  get file_a_support_ticket(): Locator { return LocatorManager.resolve(this.page, "file_a_support_ticket"); }
  get file_a_support_ticket_2(): Locator { return LocatorManager.resolve(this.page, "file_a_support_ticket_2"); }
  get filter_all(): Locator { return LocatorManager.resolve(this.page, "filter_all"); }
  get financial_services_develop_innovative_and_secure(): Locator { return LocatorManager.resolve(this.page, "financial_services_develop_innovative_and_secure"); }
  get financial_services_intuit_unifies_support_for(): Locator { return LocatorManager.resolve(this.page, "financial_services_intuit_unifies_support_for"); }
  get games_enable_game_development_for_every_genre_and(): Locator { return LocatorManager.resolve(this.page, "games_enable_game_development_for_every_genre_and"); }
  get geographic_regions_9(): Locator { return LocatorManager.resolve(this.page, "geographic_regions_9"); }
  get getting_started(): Locator { return LocatorManager.resolve(this.page, "getting_started"); }
  get government_solutions_designed_to_help_government(): Locator { return LocatorManager.resolve(this.page, "government_solutions_designed_to_help_government"); }
  get healthcare_and_life_sciences_accelerate(): Locator { return LocatorManager.resolve(this.page, "healthcare_and_life_sciences_accelerate"); }
  get here(): Locator { return LocatorManager.resolve(this.page, "here"); }
  get hi_i_can_connect_you_with_an_aws_representative(): Locator { return LocatorManager.resolve(this.page, "hi_i_can_connect_you_with_an_aws_representative"); }
  get input_loc_0001(): Locator { return LocatorManager.resolve(this.page, "input_loc_0001"); }
  get input_loc_0002(): Locator { return LocatorManager.resolve(this.page, "input_loc_0002"); }
  get input_loc_0003(): Locator { return LocatorManager.resolve(this.page, "input_loc_0003"); }
  get input_loc_0004(): Locator { return LocatorManager.resolve(this.page, "input_loc_0004"); }
  get input_loc_0005(): Locator { return LocatorManager.resolve(this.page, "input_loc_0005"); }
  get input_loc_0006(): Locator { return LocatorManager.resolve(this.page, "input_loc_0006"); }
  get input_loc_0007(): Locator { return LocatorManager.resolve(this.page, "input_loc_0007"); }
  get input_loc_0008(): Locator { return LocatorManager.resolve(this.page, "input_loc_0008"); }
  get input_loc_0009(): Locator { return LocatorManager.resolve(this.page, "input_loc_0009"); }
  get java_on_aws(): Locator { return LocatorManager.resolve(this.page, "java_on_aws"); }
  get java_on_aws_2(): Locator { return LocatorManager.resolve(this.page, "java_on_aws_2"); }
  get javascript_on_aws(): Locator { return LocatorManager.resolve(this.page, "javascript_on_aws"); }
  get javascript_on_aws_2(): Locator { return LocatorManager.resolve(this.page, "javascript_on_aws_2"); }
  get knowledge_center(): Locator { return LocatorManager.resolve(this.page, "knowledge_center"); }
  get knowledge_center_3(): Locator { return LocatorManager.resolve(this.page, "knowledge_center_3"); }
  get legal(): Locator { return LocatorManager.resolve(this.page, "legal"); }
  get legal_3(): Locator { return LocatorManager.resolve(this.page, "legal_3"); }
  get media_and_entertainment_transform_media(): Locator { return LocatorManager.resolve(this.page, "media_and_entertainment_transform_media"); }
  get mexico_central(): Locator { return LocatorManager.resolve(this.page, "mexico_central"); }
  get middle_east(): Locator { return LocatorManager.resolve(this.page, "middle_east"); }
  get my_account(): Locator { return LocatorManager.resolve(this.page, "my_account"); }
  get navigate_products(): Locator { return LocatorManager.resolve(this.page, "navigate_products"); }
  get navigate_products_2(): Locator { return LocatorManager.resolve(this.page, "navigate_products_2"); }
  get navigate_products_3(): Locator { return LocatorManager.resolve(this.page, "navigate_products_3"); }
  get navigate_products_4(): Locator { return LocatorManager.resolve(this.page, "navigate_products_4"); }
  get net_on_aws(): Locator { return LocatorManager.resolve(this.page, "net_on_aws"); }
  get net_on_aws_2(): Locator { return LocatorManager.resolve(this.page, "net_on_aws_2"); }
  get no(): Locator { return LocatorManager.resolve(this.page, "no"); }
  get north_america(): Locator { return LocatorManager.resolve(this.page, "north_america"); }
  get php_on_aws(): Locator { return LocatorManager.resolve(this.page, "php_on_aws"); }
  get php_on_aws_2(): Locator { return LocatorManager.resolve(this.page, "php_on_aws_2"); }
  get press_releases(): Locator { return LocatorManager.resolve(this.page, "press_releases"); }
  get pricing(): Locator { return LocatorManager.resolve(this.page, "pricing"); }
  get privacy(): Locator { return LocatorManager.resolve(this.page, "privacy"); }
  get privacy_3(): Locator { return LocatorManager.resolve(this.page, "privacy_3"); }
  get python_on_aws(): Locator { return LocatorManager.resolve(this.page, "python_on_aws"); }
  get python_on_aws_2(): Locator { return LocatorManager.resolve(this.page, "python_on_aws_2"); }
  get re_invent(): Locator { return LocatorManager.resolve(this.page, "re_invent"); }
  get resources(): Locator { return LocatorManager.resolve(this.page, "resources"); }
  get retail(): Locator { return LocatorManager.resolve(this.page, "retail"); }
  get retail_2(): Locator { return LocatorManager.resolve(this.page, "retail_2"); }
  get retail_adidas_drives_enterprise_wide(): Locator { return LocatorManager.resolve(this.page, "retail_adidas_drives_enterprise_wide"); }
  get retail_tapestry_amplifies_store_associate_voices(): Locator { return LocatorManager.resolve(this.page, "retail_tapestry_amplifies_store_associate_voices"); }
  get save_preferences(): Locator { return LocatorManager.resolve(this.page, "save_preferences"); }
  get save_preferences_2(): Locator { return LocatorManager.resolve(this.page, "save_preferences_2"); }
  get sdks_tools(): Locator { return LocatorManager.resolve(this.page, "sdks_tools"); }
  get sdks_tools_2(): Locator { return LocatorManager.resolve(this.page, "sdks_tools_2"); }
  get search(): Locator { return LocatorManager.resolve(this.page, "search"); }
  get show_8_more(): Locator { return LocatorManager.resolve(this.page, "show_8_more"); }
  get sign_in_to_console(): Locator { return LocatorManager.resolve(this.page, "sign_in_to_console"); }
  get site_terms(): Locator { return LocatorManager.resolve(this.page, "site_terms"); }
  get site_terms_3(): Locator { return LocatorManager.resolve(this.page, "site_terms_3"); }
  get skip_to_main_content(): Locator { return LocatorManager.resolve(this.page, "skip_to_main_content"); }
  get solutions(): Locator { return LocatorManager.resolve(this.page, "solutions"); }
  get south_america(): Locator { return LocatorManager.resolve(this.page, "south_america"); }
  get start_free_with_aws(): Locator { return LocatorManager.resolve(this.page, "start_free_with_aws"); }
  get support(): Locator { return LocatorManager.resolve(this.page, "support"); }
  get telecommunications_accelerate_innovation_scale(): Locator { return LocatorManager.resolve(this.page, "telecommunications_accelerate_innovation_scale"); }
  get training(): Locator { return LocatorManager.resolve(this.page, "training"); }
  get travel_hospitality_how_booking_com_personalizes(): Locator { return LocatorManager.resolve(this.page, "travel_hospitality_how_booking_com_personalizes"); }
  get travel_hospitality_how_tui_uses_amazon_connect_to(): Locator { return LocatorManager.resolve(this.page, "travel_hospitality_how_tui_uses_amazon_connect_to"); }
  get us_east_northern_virginia(): Locator { return LocatorManager.resolve(this.page, "us_east_northern_virginia"); }
  get us_east_ohio(): Locator { return LocatorManager.resolve(this.page, "us_east_ohio"); }
  get us_west_northern_california(): Locator { return LocatorManager.resolve(this.page, "us_west_northern_california"); }
  get us_west_oregon(): Locator { return LocatorManager.resolve(this.page, "us_west_oregon"); }
  get view_more_stories(): Locator { return LocatorManager.resolve(this.page, "view_more_stories"); }
  get what_is_agentic_ai(): Locator { return LocatorManager.resolve(this.page, "what_is_agentic_ai"); }
  get what_is_aws(): Locator { return LocatorManager.resolve(this.page, "what_is_aws"); }
  get what_is_cloud_computing(): Locator { return LocatorManager.resolve(this.page, "what_is_cloud_computing"); }
  get what_s_new(): Locator { return LocatorManager.resolve(this.page, "what_s_new"); }
  get yes(): Locator { return LocatorManager.resolve(this.page, "yes"); }
}

export class M02Page {
  constructor(private readonly page: Page) {}

  get _2(): Locator { return LocatorManager.resolve(this.page, "2"); }
  get _50_75_100_125_150_175_200_300_400(): Locator { return LocatorManager.resolve(this.page, "50_75_100_125_150_175_200_300_400"); }
  get a_loc_0076(): Locator { return LocatorManager.resolve(this.page, "a_loc_0076"); }
  get a_loc_0079(): Locator { return LocatorManager.resolve(this.page, "a_loc_0079"); }
  get a_loc_0143(): Locator { return LocatorManager.resolve(this.page, "a_loc_0143"); }
  get a_loc_0144(): Locator { return LocatorManager.resolve(this.page, "a_loc_0144"); }
  get a_loc_0145(): Locator { return LocatorManager.resolve(this.page, "a_loc_0145"); }
  get a_loc_0146(): Locator { return LocatorManager.resolve(this.page, "a_loc_0146"); }
  get a_loc_0147(): Locator { return LocatorManager.resolve(this.page, "a_loc_0147"); }
  get a_loc_0148(): Locator { return LocatorManager.resolve(this.page, "a_loc_0148"); }
  get a_loc_0149(): Locator { return LocatorManager.resolve(this.page, "a_loc_0149"); }
  get a_loc_0150(): Locator { return LocatorManager.resolve(this.page, "a_loc_0150"); }
  get accept_2(): Locator { return LocatorManager.resolve(this.page, "accept_2"); }
  get amazon_rds(): Locator { return LocatorManager.resolve(this.page, "amazon_rds"); }
  get analyst_reports_2(): Locator { return LocatorManager.resolve(this.page, "analyst_reports_2"); }
  get architecture_center_2(): Locator { return LocatorManager.resolve(this.page, "architecture_center_2"); }
  get audio_track(): Locator { return LocatorManager.resolve(this.page, "audio_track"); }
  get aws_accessibility_2(): Locator { return LocatorManager.resolve(this.page, "aws_accessibility_2"); }
  get aws_cloud_security_2(): Locator { return LocatorManager.resolve(this.page, "aws_cloud_security_2"); }
  get aws_cookie_notice_2(): Locator { return LocatorManager.resolve(this.page, "aws_cookie_notice_2"); }
  get aws_marketplace_2(): Locator { return LocatorManager.resolve(this.page, "aws_marketplace_2"); }
  get aws_partners_2(): Locator { return LocatorManager.resolve(this.page, "aws_partners_2"); }
  get aws_privacy_notice_2(): Locator { return LocatorManager.resolve(this.page, "aws_privacy_notice_2"); }
  get aws_solutions_library_2(): Locator { return LocatorManager.resolve(this.page, "aws_solutions_library_2"); }
  get aws_support_overview_2(): Locator { return LocatorManager.resolve(this.page, "aws_support_overview_2"); }
  get aws_trust_center_2(): Locator { return LocatorManager.resolve(this.page, "aws_trust_center_2"); }
  get back_to_top_2(): Locator { return LocatorManager.resolve(this.page, "back_to_top_2"); }
  get blackwhiteredgreenblueyellowmagentacyan(): Locator { return LocatorManager.resolve(this.page, "blackwhiteredgreenblueyellowmagentacyan"); }
  get blackwhiteredgreenblueyellowmagentacyan_2(): Locator { return LocatorManager.resolve(this.page, "blackwhiteredgreenblueyellowmagentacyan_2"); }
  get blogs_2(): Locator { return LocatorManager.resolve(this.page, "blogs_2"); }
  get bmw_increased_scalability_and_reduced_costs_with(): Locator { return LocatorManager.resolve(this.page, "bmw_increased_scalability_and_reduced_costs_with"); }
  get build_saas_applications(): Locator { return LocatorManager.resolve(this.page, "build_saas_applications"); }
  get builder_center_2(): Locator { return LocatorManager.resolve(this.page, "builder_center_2"); }
  get button_loc_0016(): Locator { return LocatorManager.resolve(this.page, "button_loc_0016"); }
  get button_loc_0017_2(): Locator { return LocatorManager.resolve(this.page, "button_loc_0017_2"); }
  get button_loc_0018_2(): Locator { return LocatorManager.resolve(this.page, "button_loc_0018_2"); }
  get button_loc_0020(): Locator { return LocatorManager.resolve(this.page, "button_loc_0020"); }
  get button_loc_0024(): Locator { return LocatorManager.resolve(this.page, "button_loc_0024"); }
  get button_loc_0030(): Locator { return LocatorManager.resolve(this.page, "button_loc_0030"); }
  get button_loc_0031_2(): Locator { return LocatorManager.resolve(this.page, "button_loc_0031_2"); }
  get button_loc_0032_2(): Locator { return LocatorManager.resolve(this.page, "button_loc_0032_2"); }
  get button_loc_0033_2(): Locator { return LocatorManager.resolve(this.page, "button_loc_0033_2"); }
  get button_loc_0049_2(): Locator { return LocatorManager.resolve(this.page, "button_loc_0049_2"); }
  get button_loc_0050_2(): Locator { return LocatorManager.resolve(this.page, "button_loc_0050_2"); }
  get button_loc_0058_2(): Locator { return LocatorManager.resolve(this.page, "button_loc_0058_2"); }
  get button_loc_0060_2(): Locator { return LocatorManager.resolve(this.page, "button_loc_0060_2"); }
  get cancel_3(): Locator { return LocatorManager.resolve(this.page, "cancel_3"); }
  get cancel_4(): Locator { return LocatorManager.resolve(this.page, "cancel_4"); }
  get captions(): Locator { return LocatorManager.resolve(this.page, "captions"); }
  get chapters(): Locator { return LocatorManager.resolve(this.page, "chapters"); }
  get close_modal_dialog(): Locator { return LocatorManager.resolve(this.page, "close_modal_dialog"); }
  get cloud_computing_concepts_hub_2(): Locator { return LocatorManager.resolve(this.page, "cloud_computing_concepts_hub_2"); }
  get coinbase_launches_an_ultra_low_latency(): Locator { return LocatorManager.resolve(this.page, "coinbase_launches_an_ultra_low_latency"); }
  get connect_with_an_aurora_specialist(): Locator { return LocatorManager.resolve(this.page, "connect_with_an_aurora_specialist"); }
  get console_start_building_in_the_console_sign_in(): Locator { return LocatorManager.resolve(this.page, "console_start_building_in_the_console_sign_in"); }
  get contact_us_3(): Locator { return LocatorManager.resolve(this.page, "contact_us_3"); }
  get cookie_notice_2(): Locator { return LocatorManager.resolve(this.page, "cookie_notice_2"); }
  get cookie_preferences_2(): Locator { return LocatorManager.resolve(this.page, "cookie_preferences_2"); }
  get create_account_2(): Locator { return LocatorManager.resolve(this.page, "create_account_2"); }
  get create_an_aws_account_2(): Locator { return LocatorManager.resolve(this.page, "create_an_aws_account_2"); }
  get customers(): Locator { return LocatorManager.resolve(this.page, "customers"); }
  get customize_2(): Locator { return LocatorManager.resolve(this.page, "customize_2"); }
  get databases(): Locator { return LocatorManager.resolve(this.page, "databases"); }
  get decline_2(): Locator { return LocatorManager.resolve(this.page, "decline_2"); }
  get deploy_globally_distributed_applications(): Locator { return LocatorManager.resolve(this.page, "deploy_globally_distributed_applications"); }
  get descriptions(): Locator { return LocatorManager.resolve(this.page, "descriptions"); }
  get discover_aws_2(): Locator { return LocatorManager.resolve(this.page, "discover_aws_2"); }
  get documentation_dive_deep_on_aurora_read_the(): Locator { return LocatorManager.resolve(this.page, "documentation_dive_deep_on_aurora_read_the"); }
  get done(): Locator { return LocatorManager.resolve(this.page, "done"); }
  get draftkings_scales_its_financial_ledger_with(): Locator { return LocatorManager.resolve(this.page, "draftkings_scales_its_financial_ledger_with"); }
  get easy_to_migrate_easily_migrate_mysql_or(): Locator { return LocatorManager.resolve(this.page, "easy_to_migrate_easily_migrate_mysql_or"); }
  get english_3(): Locator { return LocatorManager.resolve(this.page, "english_3"); }
  get english_4(): Locator { return LocatorManager.resolve(this.page, "english_4"); }
  get event_code_of_conduct_2(): Locator { return LocatorManager.resolve(this.page, "event_code_of_conduct_2"); }
  get event_terms_conditions_2(): Locator { return LocatorManager.resolve(this.page, "event_terms_conditions_2"); }
  get faqs(): Locator { return LocatorManager.resolve(this.page, "faqs"); }
  get features(): Locator { return LocatorManager.resolve(this.page, "features"); }
  get filter_all_2(): Locator { return LocatorManager.resolve(this.page, "filter_all_2"); }
  get free_tier_sign_up_for_a_free_account_try_for_free(): Locator { return LocatorManager.resolve(this.page, "free_tier_sign_up_for_a_free_account_try_for_free"); }
  get fullscreen(): Locator { return LocatorManager.resolve(this.page, "fullscreen"); }
  get get_started_with_aurora(): Locator { return LocatorManager.resolve(this.page, "get_started_with_aurora"); }
  get getting_started_2(): Locator { return LocatorManager.resolve(this.page, "getting_started_2"); }
  get go_serverless(): Locator { return LocatorManager.resolve(this.page, "go_serverless"); }
  get here_2(): Locator { return LocatorManager.resolve(this.page, "here_2"); }
  get high_availability_designed_for_up_to_99_99_single(): Locator { return LocatorManager.resolve(this.page, "high_availability_designed_for_up_to_99_99_single"); }
  get high_performance_power_internet_scale(): Locator { return LocatorManager.resolve(this.page, "high_performance_power_internet_scale"); }
  get input_loc_0001_2(): Locator { return LocatorManager.resolve(this.page, "input_loc_0001_2"); }
  get input_loc_0002_2(): Locator { return LocatorManager.resolve(this.page, "input_loc_0002_2"); }
  get input_loc_0003_2(): Locator { return LocatorManager.resolve(this.page, "input_loc_0003_2"); }
  get input_loc_0004_2(): Locator { return LocatorManager.resolve(this.page, "input_loc_0004_2"); }
  get input_loc_0005_2(): Locator { return LocatorManager.resolve(this.page, "input_loc_0005_2"); }
  get input_loc_0006_2(): Locator { return LocatorManager.resolve(this.page, "input_loc_0006_2"); }
  get input_loc_0007_2(): Locator { return LocatorManager.resolve(this.page, "input_loc_0007_2"); }
  get input_loc_0008_2(): Locator { return LocatorManager.resolve(this.page, "input_loc_0008_2"); }
  get learn_how_to_get_started(): Locator { return LocatorManager.resolve(this.page, "learn_how_to_get_started"); }
  get learn_how_to_get_started_2(): Locator { return LocatorManager.resolve(this.page, "learn_how_to_get_started_2"); }
  get legal_2(): Locator { return LocatorManager.resolve(this.page, "legal_2"); }
  get migrate_with_aws_dms(): Locator { return LocatorManager.resolve(this.page, "migrate_with_aws_dms"); }
  get modernize_enterprise_applications(): Locator { return LocatorManager.resolve(this.page, "modernize_enterprise_applications"); }
  get mute(): Locator { return LocatorManager.resolve(this.page, "mute"); }
  get my_account_2(): Locator { return LocatorManager.resolve(this.page, "my_account_2"); }
  get navigate_products_5(): Locator { return LocatorManager.resolve(this.page, "navigate_products_5"); }
  get navigate_products_6(): Locator { return LocatorManager.resolve(this.page, "navigate_products_6"); }
  get navigate_products_7(): Locator { return LocatorManager.resolve(this.page, "navigate_products_7"); }
  get navigate_products_8(): Locator { return LocatorManager.resolve(this.page, "navigate_products_8"); }
  get need_more_info_highlight_any_text_to_get_an(): Locator { return LocatorManager.resolve(this.page, "need_more_info_highlight_any_text_to_get_an"); }
  get noneraiseddepresseduniformdrop_shadow(): Locator { return LocatorManager.resolve(this.page, "noneraiseddepresseduniformdrop_shadow"); }
  get opaquesemi_transparent(): Locator { return LocatorManager.resolve(this.page, "opaquesemi_transparent"); }
  get opaquesemi_transparenttransparent(): Locator { return LocatorManager.resolve(this.page, "opaquesemi_transparenttransparent"); }
  get overview(): Locator { return LocatorManager.resolve(this.page, "overview"); }
  get picture_in_picture(): Locator { return LocatorManager.resolve(this.page, "picture_in_picture"); }
  get play(): Locator { return LocatorManager.resolve(this.page, "play"); }
  get playback_rate(): Locator { return LocatorManager.resolve(this.page, "playback_rate"); }
  get press_releases_2(): Locator { return LocatorManager.resolve(this.page, "press_releases_2"); }
  get pricing_2(): Locator { return LocatorManager.resolve(this.page, "pricing_2"); }
  get pricing_3(): Locator { return LocatorManager.resolve(this.page, "pricing_3"); }
  get privacy_2(): Locator { return LocatorManager.resolve(this.page, "privacy_2"); }
  get proportional_sans_serifmonospace_sans(): Locator { return LocatorManager.resolve(this.page, "proportional_sans_serifmonospace_sans"); }
  get re_invent_2(): Locator { return LocatorManager.resolve(this.page, "re_invent_2"); }
  get reset(): Locator { return LocatorManager.resolve(this.page, "reset"); }
  get resources_2(): Locator { return LocatorManager.resolve(this.page, "resources_2"); }
  get resources_3(): Locator { return LocatorManager.resolve(this.page, "resources_3"); }
  get resources_learn_with_hands_on_training_get(): Locator { return LocatorManager.resolve(this.page, "resources_learn_with_hands_on_training_get"); }
  get samsung_migrated_1_1_billion_users_from_oracle_to(): Locator { return LocatorManager.resolve(this.page, "samsung_migrated_1_1_billion_users_from_oracle_to"); }
  get save_preferences_3(): Locator { return LocatorManager.resolve(this.page, "save_preferences_3"); }
  get save_preferences_4(): Locator { return LocatorManager.resolve(this.page, "save_preferences_4"); }
  get scale_and_build_with_ease_automatically_scale_to(): Locator { return LocatorManager.resolve(this.page, "scale_and_build_with_ease_automatically_scale_to"); }
  get see_more_customer_stories(): Locator { return LocatorManager.resolve(this.page, "see_more_customer_stories"); }
  get seek_to_live_currently_behind_livelive(): Locator { return LocatorManager.resolve(this.page, "seek_to_live_currently_behind_livelive"); }
  get sign_in_to_console_2(): Locator { return LocatorManager.resolve(this.page, "sign_in_to_console_2"); }
  get site_terms_2(): Locator { return LocatorManager.resolve(this.page, "site_terms_2"); }
  get skip_backward(): Locator { return LocatorManager.resolve(this.page, "skip_backward"); }
  get skip_forward(): Locator { return LocatorManager.resolve(this.page, "skip_forward"); }
  get skip_to_main_content_2(): Locator { return LocatorManager.resolve(this.page, "skip_to_main_content_2"); }
  get solutions_2(): Locator { return LocatorManager.resolve(this.page, "solutions_2"); }
  get support_2(): Locator { return LocatorManager.resolve(this.page, "support_2"); }
  get training_2(): Locator { return LocatorManager.resolve(this.page, "training_2"); }
  get transparentsemi_transparentopaque(): Locator { return LocatorManager.resolve(this.page, "transparentsemi_transparentopaque"); }
  get what_is_agentic_ai_2(): Locator { return LocatorManager.resolve(this.page, "what_is_agentic_ai_2"); }
  get what_is_aws_2(): Locator { return LocatorManager.resolve(this.page, "what_is_aws_2"); }
  get what_is_cloud_computing_2(): Locator { return LocatorManager.resolve(this.page, "what_is_cloud_computing_2"); }
  get what_s_new_2(): Locator { return LocatorManager.resolve(this.page, "what_s_new_2"); }
  get whiteblackredgreenblueyellowmagentacyan(): Locator { return LocatorManager.resolve(this.page, "whiteblackredgreenblueyellowmagentacyan"); }
}

export class M03Page {
  constructor(private readonly page: Page) {}

  get _2013_03_26_aws_cloudhsm_hardware_based_key(): Locator { return LocatorManager.resolve(this.page, "2013_03_26_aws_cloudhsm_hardware_based_key"); }
  get _2014_07_10_amazon_cognito_identity_management_for(): Locator { return LocatorManager.resolve(this.page, "2014_07_10_amazon_cognito_identity_management_for"); }
  get _2017_06_07_aws_iot_greengrass_local_compute(): Locator { return LocatorManager.resolve(this.page, "2017_06_07_aws_iot_greengrass_local_compute"); }
  get _2019_12_03_amazon_detective_investigate_potential(): Locator { return LocatorManager.resolve(this.page, "2019_12_03_amazon_detective_investigate_potential"); }
  get _2020_11_19_aws_network_firewall_deploy_network(): Locator { return LocatorManager.resolve(this.page, "2020_11_19_aws_network_firewall_deploy_network"); }
  get _2021_04_08_amazon_nimble_studio_accelerate(): Locator { return LocatorManager.resolve(this.page, "2021_04_08_amazon_nimble_studio_accelerate"); }
  get _2021_11_29_amazon_inspector_automated_and(): Locator { return LocatorManager.resolve(this.page, "2021_11_29_amazon_inspector_automated_and"); }
  get _2_2(): Locator { return LocatorManager.resolve(this.page, "2_2"); }
  get a_loc_0052(): Locator { return LocatorManager.resolve(this.page, "a_loc_0052"); }
  get a_loc_0055(): Locator { return LocatorManager.resolve(this.page, "a_loc_0055"); }
  get a_loc_0070(): Locator { return LocatorManager.resolve(this.page, "a_loc_0070"); }
  get a_loc_0071(): Locator { return LocatorManager.resolve(this.page, "a_loc_0071"); }
  get a_loc_0072(): Locator { return LocatorManager.resolve(this.page, "a_loc_0072"); }
  get a_loc_0073(): Locator { return LocatorManager.resolve(this.page, "a_loc_0073"); }
  get accept_3(): Locator { return LocatorManager.resolve(this.page, "accept_3"); }
  get analyst_reports_3(): Locator { return LocatorManager.resolve(this.page, "analyst_reports_3"); }
  get architecture_center_3(): Locator { return LocatorManager.resolve(this.page, "architecture_center_3"); }
  get aws_cloud_security_3(): Locator { return LocatorManager.resolve(this.page, "aws_cloud_security_3"); }
  get aws_cookie_notice_3(): Locator { return LocatorManager.resolve(this.page, "aws_cookie_notice_3"); }
  get aws_marketplace_3(): Locator { return LocatorManager.resolve(this.page, "aws_marketplace_3"); }
  get aws_partners_3(): Locator { return LocatorManager.resolve(this.page, "aws_partners_3"); }
  get aws_pricing_calculator(): Locator { return LocatorManager.resolve(this.page, "aws_pricing_calculator"); }
  get aws_privacy_notice_3(): Locator { return LocatorManager.resolve(this.page, "aws_privacy_notice_3"); }
  get aws_private_pricing_program_amazon_com(): Locator { return LocatorManager.resolve(this.page, "aws_private_pricing_program_amazon_com"); }
  get aws_solutions_library_3(): Locator { return LocatorManager.resolve(this.page, "aws_solutions_library_3"); }
  get aws_trust_center_3(): Locator { return LocatorManager.resolve(this.page, "aws_trust_center_3"); }
  get back_to_top_3(): Locator { return LocatorManager.resolve(this.page, "back_to_top_3"); }
  get blogs_3(): Locator { return LocatorManager.resolve(this.page, "blogs_3"); }
  get builder_center_3(): Locator { return LocatorManager.resolve(this.page, "builder_center_3"); }
  get button_loc_0017_3(): Locator { return LocatorManager.resolve(this.page, "button_loc_0017_3"); }
  get button_loc_0018_3(): Locator { return LocatorManager.resolve(this.page, "button_loc_0018_3"); }
  get button_loc_0019_2(): Locator { return LocatorManager.resolve(this.page, "button_loc_0019_2"); }
  get button_loc_0021_2(): Locator { return LocatorManager.resolve(this.page, "button_loc_0021_2"); }
  get button_loc_0025_2(): Locator { return LocatorManager.resolve(this.page, "button_loc_0025_2"); }
  get button_loc_0031_3(): Locator { return LocatorManager.resolve(this.page, "button_loc_0031_3"); }
  get button_loc_0032_3(): Locator { return LocatorManager.resolve(this.page, "button_loc_0032_3"); }
  get button_loc_0033_3(): Locator { return LocatorManager.resolve(this.page, "button_loc_0033_3"); }
  get button_loc_0043(): Locator { return LocatorManager.resolve(this.page, "button_loc_0043"); }
  get button_loc_0045_2(): Locator { return LocatorManager.resolve(this.page, "button_loc_0045_2"); }
  get cancel_5(): Locator { return LocatorManager.resolve(this.page, "cancel_5"); }
  get cancel_6(): Locator { return LocatorManager.resolve(this.page, "cancel_6"); }
  get cancel_8(): Locator { return LocatorManager.resolve(this.page, "cancel_8"); }
  get cloud_computing_concepts_hub_3(): Locator { return LocatorManager.resolve(this.page, "cloud_computing_concepts_hub_3"); }
  get contact_us_6(): Locator { return LocatorManager.resolve(this.page, "contact_us_6"); }
  get cookie_notice_3(): Locator { return LocatorManager.resolve(this.page, "cookie_notice_3"); }
  get cost_optimization(): Locator { return LocatorManager.resolve(this.page, "cost_optimization"); }
  get create_account_3(): Locator { return LocatorManager.resolve(this.page, "create_account_3"); }
  get create_an_aws_account_3(): Locator { return LocatorManager.resolve(this.page, "create_an_aws_account_3"); }
  get customize_3(): Locator { return LocatorManager.resolve(this.page, "customize_3"); }
  get decline_3(): Locator { return LocatorManager.resolve(this.page, "decline_3"); }
  get discover_aws_3(): Locator { return LocatorManager.resolve(this.page, "discover_aws_3"); }
  get english_5(): Locator { return LocatorManager.resolve(this.page, "english_5"); }
  get english_6(): Locator { return LocatorManager.resolve(this.page, "english_6"); }
  get file_a_support_ticket_3(): Locator { return LocatorManager.resolve(this.page, "file_a_support_ticket_3"); }
  get filter(): Locator { return LocatorManager.resolve(this.page, "filter"); }
  get filter_all_3(): Locator { return LocatorManager.resolve(this.page, "filter_all_3"); }
  get flat_rate(): Locator { return LocatorManager.resolve(this.page, "flat_rate"); }
  get free_tier(): Locator { return LocatorManager.resolve(this.page, "free_tier"); }
  get get_started_for_free(): Locator { return LocatorManager.resolve(this.page, "get_started_for_free"); }
  get getting_started_3(): Locator { return LocatorManager.resolve(this.page, "getting_started_3"); }
  get here_3(): Locator { return LocatorManager.resolve(this.page, "here_3"); }
  get hi_i_can_connect_you_with_an_aws_representative_2(): Locator { return LocatorManager.resolve(this.page, "hi_i_can_connect_you_with_an_aws_representative_2"); }
  get home(): Locator { return LocatorManager.resolve(this.page, "home"); }
  get input_loc_0001_3(): Locator { return LocatorManager.resolve(this.page, "input_loc_0001_3"); }
  get input_loc_0002_3(): Locator { return LocatorManager.resolve(this.page, "input_loc_0002_3"); }
  get input_loc_0003_3(): Locator { return LocatorManager.resolve(this.page, "input_loc_0003_3"); }
  get input_loc_0004_3(): Locator { return LocatorManager.resolve(this.page, "input_loc_0004_3"); }
  get input_loc_0005_3(): Locator { return LocatorManager.resolve(this.page, "input_loc_0005_3"); }
  get input_loc_0006_3(): Locator { return LocatorManager.resolve(this.page, "input_loc_0006_3"); }
  get input_loc_0007_3(): Locator { return LocatorManager.resolve(this.page, "input_loc_0007_3"); }
  get input_loc_0008_3(): Locator { return LocatorManager.resolve(this.page, "input_loc_0008_3"); }
  get input_loc_0009_2(): Locator { return LocatorManager.resolve(this.page, "input_loc_0009_2"); }
  get java_on_aws_3(): Locator { return LocatorManager.resolve(this.page, "java_on_aws_3"); }
  get javascript_on_aws_3(): Locator { return LocatorManager.resolve(this.page, "javascript_on_aws_3"); }
  get learn_more_about_flat_rate_pricing(): Locator { return LocatorManager.resolve(this.page, "learn_more_about_flat_rate_pricing"); }
  get learn_more_about_savings_plans_here(): Locator { return LocatorManager.resolve(this.page, "learn_more_about_savings_plans_here"); }
  get learn_more_about_tiered_pricing(): Locator { return LocatorManager.resolve(this.page, "learn_more_about_tiered_pricing"); }
  get my_account_3(): Locator { return LocatorManager.resolve(this.page, "my_account_3"); }
  get navigate_products_10(): Locator { return LocatorManager.resolve(this.page, "navigate_products_10"); }
  get navigate_products_11(): Locator { return LocatorManager.resolve(this.page, "navigate_products_11"); }
  get navigate_products_9(): Locator { return LocatorManager.resolve(this.page, "navigate_products_9"); }
  get need_more_info_highlight_any_text_to_get_an_2(): Locator { return LocatorManager.resolve(this.page, "need_more_info_highlight_any_text_to_get_an_2"); }
  get net_on_aws_3(): Locator { return LocatorManager.resolve(this.page, "net_on_aws_3"); }
  get overview_2(): Locator { return LocatorManager.resolve(this.page, "overview_2"); }
  get pay_as_you_go(): Locator { return LocatorManager.resolve(this.page, "pay_as_you_go"); }
  get pay_less_by_using_more(): Locator { return LocatorManager.resolve(this.page, "pay_less_by_using_more"); }
  get php_on_aws_3(): Locator { return LocatorManager.resolve(this.page, "php_on_aws_3"); }
  get press_releases_3(): Locator { return LocatorManager.resolve(this.page, "press_releases_3"); }
  get pricing_4(): Locator { return LocatorManager.resolve(this.page, "pricing_4"); }
  get python_on_aws_3(): Locator { return LocatorManager.resolve(this.page, "python_on_aws_3"); }
  get re_invent_3(): Locator { return LocatorManager.resolve(this.page, "re_invent_3"); }
  get request_a_pricing_quote(): Locator { return LocatorManager.resolve(this.page, "request_a_pricing_quote"); }
  get resources_4(): Locator { return LocatorManager.resolve(this.page, "resources_4"); }
  get resources_5(): Locator { return LocatorManager.resolve(this.page, "resources_5"); }
  get save_preferences_5(): Locator { return LocatorManager.resolve(this.page, "save_preferences_5"); }
  get save_preferences_6(): Locator { return LocatorManager.resolve(this.page, "save_preferences_6"); }
  get save_when_you_commit(): Locator { return LocatorManager.resolve(this.page, "save_when_you_commit"); }
  get sdks_tools_3(): Locator { return LocatorManager.resolve(this.page, "sdks_tools_3"); }
  get show_8_more_2(): Locator { return LocatorManager.resolve(this.page, "show_8_more_2"); }
  get sign_in_to_console_3(): Locator { return LocatorManager.resolve(this.page, "sign_in_to_console_3"); }
  get skip_to_main_content_3(): Locator { return LocatorManager.resolve(this.page, "skip_to_main_content_3"); }
  get solutions_3(): Locator { return LocatorManager.resolve(this.page, "solutions_3"); }
  get start_using_the_aws_pricing_calculator(): Locator { return LocatorManager.resolve(this.page, "start_using_the_aws_pricing_calculator"); }
  get support_3(): Locator { return LocatorManager.resolve(this.page, "support_3"); }
  get training_3(): Locator { return LocatorManager.resolve(this.page, "training_3"); }
  get what_is_agentic_ai_3(): Locator { return LocatorManager.resolve(this.page, "what_is_agentic_ai_3"); }
  get what_is_aws_3(): Locator { return LocatorManager.resolve(this.page, "what_is_aws_3"); }
  get what_is_cloud_computing_3(): Locator { return LocatorManager.resolve(this.page, "what_is_cloud_computing_3"); }
  get what_s_new_3(): Locator { return LocatorManager.resolve(this.page, "what_s_new_3"); }
}

export class M04Page {
  constructor(private readonly page: Page) {}

  get _2_3(): Locator { return LocatorManager.resolve(this.page, "2_3"); }
  get _50_75_100_125_150_175_200_300_400_2(): Locator { return LocatorManager.resolve(this.page, "50_75_100_125_150_175_200_300_400_2"); }
  get a_loc_0065(): Locator { return LocatorManager.resolve(this.page, "a_loc_0065"); }
  get a_loc_0068(): Locator { return LocatorManager.resolve(this.page, "a_loc_0068"); }
  get a_loc_0080(): Locator { return LocatorManager.resolve(this.page, "a_loc_0080"); }
  get a_loc_0080_2(): Locator { return LocatorManager.resolve(this.page, "a_loc_0080_2"); }
  get a_loc_0080_3(): Locator { return LocatorManager.resolve(this.page, "a_loc_0080_3"); }
  get accept_4(): Locator { return LocatorManager.resolve(this.page, "accept_4"); }
  get analyst_reports_4(): Locator { return LocatorManager.resolve(this.page, "analyst_reports_4"); }
  get architecture_center_4(): Locator { return LocatorManager.resolve(this.page, "architecture_center_4"); }
  get audio_track_2(): Locator { return LocatorManager.resolve(this.page, "audio_track_2"); }
  get aws(): Locator { return LocatorManager.resolve(this.page, "aws"); }
  get aws_accessibility_4(): Locator { return LocatorManager.resolve(this.page, "aws_accessibility_4"); }
  get aws_cloud_security_4(): Locator { return LocatorManager.resolve(this.page, "aws_cloud_security_4"); }
  get aws_cookie_notice_4(): Locator { return LocatorManager.resolve(this.page, "aws_cookie_notice_4"); }
  get aws_marketplace_4(): Locator { return LocatorManager.resolve(this.page, "aws_marketplace_4"); }
  get aws_partner_central(): Locator { return LocatorManager.resolve(this.page, "aws_partner_central"); }
  get aws_partners_4(): Locator { return LocatorManager.resolve(this.page, "aws_partners_4"); }
  get aws_privacy_notice_4(): Locator { return LocatorManager.resolve(this.page, "aws_privacy_notice_4"); }
  get aws_re_post_2(): Locator { return LocatorManager.resolve(this.page, "aws_re_post_2"); }
  get aws_re_post_4(): Locator { return LocatorManager.resolve(this.page, "aws_re_post_4"); }
  get aws_solutions_library_4(): Locator { return LocatorManager.resolve(this.page, "aws_solutions_library_4"); }
  get aws_support_overview_4(): Locator { return LocatorManager.resolve(this.page, "aws_support_overview_4"); }
  get aws_trust_center_4(): Locator { return LocatorManager.resolve(this.page, "aws_trust_center_4"); }
  get back_to_top_4(): Locator { return LocatorManager.resolve(this.page, "back_to_top_4"); }
  get bcg_generates_65_of_regional_sales_pipeline_with(): Locator { return LocatorManager.resolve(this.page, "bcg_generates_65_of_regional_sales_pipeline_with"); }
  get become_an_aws_partner(): Locator { return LocatorManager.resolve(this.page, "become_an_aws_partner"); }
  get blackwhiteredgreenblueyellowmagentacyan_3(): Locator { return LocatorManager.resolve(this.page, "blackwhiteredgreenblueyellowmagentacyan_3"); }
  get blackwhiteredgreenblueyellowmagentacyan_4(): Locator { return LocatorManager.resolve(this.page, "blackwhiteredgreenblueyellowmagentacyan_4"); }
  get blog_apn_blog_see_all_posts(): Locator { return LocatorManager.resolve(this.page, "blog_apn_blog_see_all_posts"); }
  get blog_learn_about_the_aws_partner_experience(): Locator { return LocatorManager.resolve(this.page, "blog_learn_about_the_aws_partner_experience"); }
  get blogs_4(): Locator { return LocatorManager.resolve(this.page, "blogs_4"); }
  get builder_center_4(): Locator { return LocatorManager.resolve(this.page, "builder_center_4"); }
  get button_loc_0014(): Locator { return LocatorManager.resolve(this.page, "button_loc_0014"); }
  get button_loc_0015(): Locator { return LocatorManager.resolve(this.page, "button_loc_0015"); }
  get button_loc_0016_2(): Locator { return LocatorManager.resolve(this.page, "button_loc_0016_2"); }
  get button_loc_0016_3(): Locator { return LocatorManager.resolve(this.page, "button_loc_0016_3"); }
  get button_loc_0016_4(): Locator { return LocatorManager.resolve(this.page, "button_loc_0016_4"); }
  get button_loc_0016_5(): Locator { return LocatorManager.resolve(this.page, "button_loc_0016_5"); }
  get button_loc_0016_6(): Locator { return LocatorManager.resolve(this.page, "button_loc_0016_6"); }
  get button_loc_0016_7(): Locator { return LocatorManager.resolve(this.page, "button_loc_0016_7"); }
  get button_loc_0016_8(): Locator { return LocatorManager.resolve(this.page, "button_loc_0016_8"); }
  get button_loc_0016_9(): Locator { return LocatorManager.resolve(this.page, "button_loc_0016_9"); }
  get button_loc_0026(): Locator { return LocatorManager.resolve(this.page, "button_loc_0026"); }
  get button_loc_0048_2(): Locator { return LocatorManager.resolve(this.page, "button_loc_0048_2"); }
  get button_loc_0048_3(): Locator { return LocatorManager.resolve(this.page, "button_loc_0048_3"); }
  get cancel_7(): Locator { return LocatorManager.resolve(this.page, "cancel_7"); }
  get captions_2(): Locator { return LocatorManager.resolve(this.page, "captions_2"); }
  get chapters_2(): Locator { return LocatorManager.resolve(this.page, "chapters_2"); }
  get close_modal_dialog_2(): Locator { return LocatorManager.resolve(this.page, "close_modal_dialog_2"); }
  get cloud_computing_concepts_hub_4(): Locator { return LocatorManager.resolve(this.page, "cloud_computing_concepts_hub_4"); }
  get co_sell_with_aws(): Locator { return LocatorManager.resolve(this.page, "co_sell_with_aws"); }
  get contact_us_7(): Locator { return LocatorManager.resolve(this.page, "contact_us_7"); }
  get cookie_notice_4(): Locator { return LocatorManager.resolve(this.page, "cookie_notice_4"); }
  get cookie_preferences_4(): Locator { return LocatorManager.resolve(this.page, "cookie_preferences_4"); }
  get create_account_4(): Locator { return LocatorManager.resolve(this.page, "create_account_4"); }
  get create_an_aws_account_4(): Locator { return LocatorManager.resolve(this.page, "create_an_aws_account_4"); }
  get customize_4(): Locator { return LocatorManager.resolve(this.page, "customize_4"); }
  get decline_4(): Locator { return LocatorManager.resolve(this.page, "decline_4"); }
  get descriptions_2(): Locator { return LocatorManager.resolve(this.page, "descriptions_2"); }
  get discover_aws_4(): Locator { return LocatorManager.resolve(this.page, "discover_aws_4"); }
  get done_2(): Locator { return LocatorManager.resolve(this.page, "done_2"); }
  get drive_profitable_growth(): Locator { return LocatorManager.resolve(this.page, "drive_profitable_growth"); }
  get english_7(): Locator { return LocatorManager.resolve(this.page, "english_7"); }
  get english_8(): Locator { return LocatorManager.resolve(this.page, "english_8"); }
  get event_code_of_conduct_4(): Locator { return LocatorManager.resolve(this.page, "event_code_of_conduct_4"); }
  get event_terms_conditions_4(): Locator { return LocatorManager.resolve(this.page, "event_terms_conditions_4"); }
  get events_attend_webinars_virtual_workshops_and_in(): Locator { return LocatorManager.resolve(this.page, "events_attend_webinars_virtual_workshops_and_in"); }
  get explore_all_success_stories(): Locator { return LocatorManager.resolve(this.page, "explore_all_success_stories"); }
  get explore_partner_programs(): Locator { return LocatorManager.resolve(this.page, "explore_partner_programs"); }
  get file_a_support_ticket_4(): Locator { return LocatorManager.resolve(this.page, "file_a_support_ticket_4"); }
  get filter_all_4(): Locator { return LocatorManager.resolve(this.page, "filter_all_4"); }
  get fullscreen_2(): Locator { return LocatorManager.resolve(this.page, "fullscreen_2"); }
  get getting_started_4(): Locator { return LocatorManager.resolve(this.page, "getting_started_4"); }
  get here_4(): Locator { return LocatorManager.resolve(this.page, "here_4"); }
  get hi_i_can_connect_you_with_an_aws_representative_3(): Locator { return LocatorManager.resolve(this.page, "hi_i_can_connect_you_with_an_aws_representative_3"); }
  get innovate(): Locator { return LocatorManager.resolve(this.page, "innovate"); }
  get input_loc_0001_4(): Locator { return LocatorManager.resolve(this.page, "input_loc_0001_4"); }
  get input_loc_0002_4(): Locator { return LocatorManager.resolve(this.page, "input_loc_0002_4"); }
  get input_loc_0003_4(): Locator { return LocatorManager.resolve(this.page, "input_loc_0003_4"); }
  get input_loc_0004_4(): Locator { return LocatorManager.resolve(this.page, "input_loc_0004_4"); }
  get input_loc_0004_5(): Locator { return LocatorManager.resolve(this.page, "input_loc_0004_5"); }
  get input_loc_0005_4(): Locator { return LocatorManager.resolve(this.page, "input_loc_0005_4"); }
  get input_loc_0006_4(): Locator { return LocatorManager.resolve(this.page, "input_loc_0006_4"); }
  get input_loc_0007_4(): Locator { return LocatorManager.resolve(this.page, "input_loc_0007_4"); }
  get java_on_aws_4(): Locator { return LocatorManager.resolve(this.page, "java_on_aws_4"); }
  get javascript_on_aws_4(): Locator { return LocatorManager.resolve(this.page, "javascript_on_aws_4"); }
  get knowledge_center_2(): Locator { return LocatorManager.resolve(this.page, "knowledge_center_2"); }
  get knowledge_center_4(): Locator { return LocatorManager.resolve(this.page, "knowledge_center_4"); }
  get l_quipe_launches_19_olympic_podcasts_in_under_30(): Locator { return LocatorManager.resolve(this.page, "l_quipe_launches_19_olympic_podcasts_in_under_30"); }
  get legal_4(): Locator { return LocatorManager.resolve(this.page, "legal_4"); }
  get live_and_on_demand_partner_webinars_watch_webinars(): Locator { return LocatorManager.resolve(this.page, "live_and_on_demand_partner_webinars_watch_webinars"); }
  get mute_2(): Locator { return LocatorManager.resolve(this.page, "mute_2"); }
  get my_account_4(): Locator { return LocatorManager.resolve(this.page, "my_account_4"); }
  get navigate_products_12(): Locator { return LocatorManager.resolve(this.page, "navigate_products_12"); }
  get navigate_products_13(): Locator { return LocatorManager.resolve(this.page, "navigate_products_13"); }
  get need_more_info_highlight_any_text_to_get_an_3(): Locator { return LocatorManager.resolve(this.page, "need_more_info_highlight_any_text_to_get_an_3"); }
  get net_on_aws_4(): Locator { return LocatorManager.resolve(this.page, "net_on_aws_4"); }
  get noneraiseddepresseduniformdrop_shadow_2(): Locator { return LocatorManager.resolve(this.page, "noneraiseddepresseduniformdrop_shadow_2"); }
  get opaquesemi_transparent_2(): Locator { return LocatorManager.resolve(this.page, "opaquesemi_transparent_2"); }
  get opaquesemi_transparenttransparent_2(): Locator { return LocatorManager.resolve(this.page, "opaquesemi_transparenttransparent_2"); }
  get overview_3(): Locator { return LocatorManager.resolve(this.page, "overview_3"); }
  get partner_paths(): Locator { return LocatorManager.resolve(this.page, "partner_paths"); }
  get partner_programs(): Locator { return LocatorManager.resolve(this.page, "partner_programs"); }
  get partnercasts_hear_from_aws_partner_teams_on_the(): Locator { return LocatorManager.resolve(this.page, "partnercasts_hear_from_aws_partner_teams_on_the"); }
  get php_on_aws_4(): Locator { return LocatorManager.resolve(this.page, "php_on_aws_4"); }
  get picture_in_picture_2(): Locator { return LocatorManager.resolve(this.page, "picture_in_picture_2"); }
  get play_2(): Locator { return LocatorManager.resolve(this.page, "play_2"); }
  get playback_rate_2(): Locator { return LocatorManager.resolve(this.page, "playback_rate_2"); }
  get press_releases_4(): Locator { return LocatorManager.resolve(this.page, "press_releases_4"); }
  get pricing_5(): Locator { return LocatorManager.resolve(this.page, "pricing_5"); }
  get privacy_4(): Locator { return LocatorManager.resolve(this.page, "privacy_4"); }
  get proportional_sans_serifmonospace_sans_2(): Locator { return LocatorManager.resolve(this.page, "proportional_sans_serifmonospace_sans_2"); }
  get python_on_aws_4(): Locator { return LocatorManager.resolve(this.page, "python_on_aws_4"); }
  get re_invent_4(): Locator { return LocatorManager.resolve(this.page, "re_invent_4"); }
  get reach_millions_of_aws_customers(): Locator { return LocatorManager.resolve(this.page, "reach_millions_of_aws_customers"); }
  get reset_2(): Locator { return LocatorManager.resolve(this.page, "reset_2"); }
  get resources_6(): Locator { return LocatorManager.resolve(this.page, "resources_6"); }
  get resources_7(): Locator { return LocatorManager.resolve(this.page, "resources_7"); }
  get save_preferences_7(): Locator { return LocatorManager.resolve(this.page, "save_preferences_7"); }
  get save_preferences_8(): Locator { return LocatorManager.resolve(this.page, "save_preferences_8"); }
  get sdks_tools_4(): Locator { return LocatorManager.resolve(this.page, "sdks_tools_4"); }
  get see_all_resources(): Locator { return LocatorManager.resolve(this.page, "see_all_resources"); }
  get seek_to_live_currently_behind_livelive_2(): Locator { return LocatorManager.resolve(this.page, "seek_to_live_currently_behind_livelive_2"); }
  get sell_in_aws_marketplace(): Locator { return LocatorManager.resolve(this.page, "sell_in_aws_marketplace"); }
  get sell_in_aws_marketplace_2(): Locator { return LocatorManager.resolve(this.page, "sell_in_aws_marketplace_2"); }
  get sign_in_to_console_4(): Locator { return LocatorManager.resolve(this.page, "sign_in_to_console_4"); }
  get sign_in_to_the_aws_console(): Locator { return LocatorManager.resolve(this.page, "sign_in_to_the_aws_console"); }
  get site_terms_4(): Locator { return LocatorManager.resolve(this.page, "site_terms_4"); }
  get skip_backward_2(): Locator { return LocatorManager.resolve(this.page, "skip_backward_2"); }
  get skip_forward_2(): Locator { return LocatorManager.resolve(this.page, "skip_forward_2"); }
  get skip_to_main_content_4(): Locator { return LocatorManager.resolve(this.page, "skip_to_main_content_4"); }
  get social_apn_linkedin_stay_connected(): Locator { return LocatorManager.resolve(this.page, "social_apn_linkedin_stay_connected"); }
  get social_apn_twitter_get_the_latest_updates(): Locator { return LocatorManager.resolve(this.page, "social_apn_twitter_get_the_latest_updates"); }
  get solutions_4(): Locator { return LocatorManager.resolve(this.page, "solutions_4"); }
  get state_of_idaho_consolidates_75_systems_into(): Locator { return LocatorManager.resolve(this.page, "state_of_idaho_consolidates_75_systems_into"); }
  get success_stories(): Locator { return LocatorManager.resolve(this.page, "success_stories"); }
  get support_4(): Locator { return LocatorManager.resolve(this.page, "support_4"); }
  get the_network_achieves_85_model_accuracy_in(): Locator { return LocatorManager.resolve(this.page, "the_network_achieves_85_model_accuracy_in"); }
  get training_4(): Locator { return LocatorManager.resolve(this.page, "training_4"); }
  get transparentsemi_transparentopaque_2(): Locator { return LocatorManager.resolve(this.page, "transparentsemi_transparentopaque_2"); }
  get video_aws_partner_network_youtube_channel_get_the(): Locator { return LocatorManager.resolve(this.page, "video_aws_partner_network_youtube_channel_get_the"); }
  get what_is_agentic_ai_4(): Locator { return LocatorManager.resolve(this.page, "what_is_agentic_ai_4"); }
  get what_is_aws_4(): Locator { return LocatorManager.resolve(this.page, "what_is_aws_4"); }
  get what_is_cloud_computing_4(): Locator { return LocatorManager.resolve(this.page, "what_is_cloud_computing_4"); }
  get what_s_new_4(): Locator { return LocatorManager.resolve(this.page, "what_s_new_4"); }
  get what_s_new_posts_read_about_the_latest(): Locator { return LocatorManager.resolve(this.page, "what_s_new_posts_read_about_the_latest"); }
  get whiteblackredgreenblueyellowmagentacyan_2(): Locator { return LocatorManager.resolve(this.page, "whiteblackredgreenblueyellowmagentacyan_2"); }
  get work_with_an_aws_partner(): Locator { return LocatorManager.resolve(this.page, "work_with_an_aws_partner"); }
}

export const PAGE_REGISTRY: Record<string, new (page: Page) => Record<string, unknown>> = {
  "M01": HomepagePage,
  "M02": M02Page,
  "M03": M03Page,
  "M04": M04Page,
};
