"""
SemanticDedupAgent — LLM-based test case deduplication.

Receives existing test cases already in the project and a list of newly
proposed test cases. Returns which proposed TCs add genuinely new coverage
and which are semantically equivalent to something that already exists.

This is a lightweight, single-prompt agent — no tools, no browser.
Called by the orchestrator after artifact_generator_testcases runs,
before any new TCs are written to disk or added to suites.
"""

import re
from typing import Dict, List, Optional

from agents.base_agent import BaseAgent
from agents.test_creation.dedup.prompt import DEDUP_PROMPT
from connectors.connector_registry import ConnectorRegistry
from tools.shared import get_logger
from tools.shared.llm_response_validator import validate_llm_json


class SemanticDedupAgent(BaseAgent):
    """Single LLM call to classify proposed TCs as new coverage or duplicates."""

    def __init__(self, settings: Optional[dict] = None):
        self.settings = settings or {}
        self._registry = ConnectorRegistry(self.settings)
        self.logger = get_logger("agent.dedup")

    def execute(self, request: dict, state: dict) -> Dict:
        """
        request must contain:
          - existing_test_cases: list[dict]  — TCs already in project_state
          - proposed_test_cases: list[dict]  — TCs just generated by artifact_generator
          - connector_mode: str (optional)
        """
        existing: List[dict] = request.get("existing_test_cases", [])
        proposed: List[dict] = request.get("proposed_test_cases", [])

        if not proposed:
            self.logger.info("No proposed test cases — dedup skipped")
            return {"module": "dedup", "status": "success", "approved": [], "rejected": []}

        if not existing:
            # Nothing to compare against — everything is new
            self.logger.info(
                f"No existing test cases — all {len(proposed)} proposed TCs approved"
            )
            return {
                "module": "dedup",
                "status": "success",
                "approved": proposed,
                "rejected": [],
            }

        connector_mode = request.get("connector_mode")
        llm = self._registry.get_llm(connector_mode)

        existing_block = _format_tc_list(existing, label="existing")
        proposed_block = _format_tc_list(proposed, label="proposed")

        prompt = DEDUP_PROMPT.format(
            existing_block=existing_block,
            proposed_block=proposed_block,
        )

        self.logger.info(
            f"Running semantic dedup: {len(existing)} existing, {len(proposed)} proposed"
        )

        try:
            raw = llm.generate(prompt)
            result = _parse_dedup_response(raw)
        except Exception as exc:
            self.logger.warning(
                f"Dedup LLM call failed ({exc}) — treating all proposed TCs as approved"
            )
            return {
                "module": "dedup",
                "status": "partial",
                "error": str(exc),
                "approved": proposed,
                "rejected": [],
            }

        # Map approved ids back to full proposed TC dicts
        approved_ids = {item.get("test_case_id", "") for item in result.get("approved", [])}
        approved_full = [tc for tc in proposed if (tc.get("test_case_id") or tc.get("id", "")) in approved_ids]
        # Any proposed TC not in approved or rejected → assume approved (safe default)
        seen_ids = approved_ids | {item.get("test_case_id", "") for item in result.get("rejected", [])}
        for tc in proposed:
            tc_id = tc.get("test_case_id") or tc.get("id", "")
            if tc_id not in seen_ids:
                approved_full.append(tc)

        self.logger.info(
            f"Dedup complete — approved: {len(approved_full)}, "
            f"rejected: {len(result.get('rejected', []))}"
        )
        for rej in result.get("rejected", []):
            self.logger.info(
                f"  REJECTED {rej.get('test_case_id')} '{rej.get('test_case_name')}' "
                f"— duplicate of {rej.get('duplicate_of')}: {rej.get('reason')}"
            )

        return {
            "module": "dedup",
            "status": "success",
            "approved": approved_full,
            "rejected": result.get("rejected", []),
            "approved_count": len(approved_full),
            "rejected_count": len(result.get("rejected", [])),
        }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _format_tc_list(tcs: List[dict], label: str) -> str:
    if not tcs:
        return f"(no {label} test cases)"
    lines = []
    for tc in tcs:
        tc_id = tc.get("test_case_id") or tc.get("id", "?")
        name = tc.get("test_case_name") or tc.get("name", "?")
        expected = tc.get("expected_result", "")
        tc_type = tc.get("test_case_type", "")
        lines.append(
            f"- [{tc_id}] {name}"
            + (f" ({tc_type})" if tc_type else "")
            + (f" → {expected}" if expected else "")
        )
    return "\n".join(lines)


def _parse_dedup_response(raw: str) -> dict:
    """Parse the JSON object from the LLM response via the shared validator; if the
    model wrapped it in prose, fall back to the outermost {...} span."""
    try:
        return validate_llm_json(raw)
    except ValueError:
        match = re.search(r"\{.*\}", raw or "", re.DOTALL)
        if not match:
            raise ValueError(f"No JSON object found in dedup response: {(raw or '')[:200]}")
        return validate_llm_json(match.group())
