"""prompt.py — LLM prompt template for SemanticDedupAgent."""

DEDUP_PROMPT = """You are a test coverage deduplicator for a software QA system.

## Existing test cases already in the project
{existing_block}

## Newly proposed test cases (just generated by the AI)
{proposed_block}

## Your task
For each proposed test case, decide:
- APPROVED: it adds genuinely NEW coverage not already present in the existing cases
- REJECTED: it is semantically equivalent to an existing test case (different wording, same intent/coverage)

Rules:
- Different credentials, boundary values, or edge conditions = APPROVED even if the scenario name is similar
- Same scenario tested the same way with only a different user name = REJECTED
- A test that exercises a new flow path = APPROVED
- Be strict: only reject when you are confident the coverage is already present

Respond ONLY with a valid JSON object in this exact shape:
{{
  "approved": [
    {{
      "test_case_id": "<proposed id>",
      "test_case_name": "<proposed name>",
      "reason": "<one sentence why this is new coverage>"
    }}
  ],
  "rejected": [
    {{
      "test_case_id": "<proposed id>",
      "test_case_name": "<proposed name>",
      "duplicate_of": "<existing TC id>",
      "reason": "<one sentence why this is a duplicate>"
    }}
  ]
}}

No extra text, no markdown fences — just the JSON object."""
