"use client";

import { use } from "react";
import { Wand2, Clock } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { ErrorState } from "@/components/shared/error-state";
import { StatusPill } from "@/components/shared/status-pill";
import { useTestCase } from "@/lib/query/hooks";

export default function TestCaseDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const { data, isLoading, isError, refetch } = useTestCase(id);

  if (isLoading) return <Skeleton className="h-96 rounded-lg" />;
  if (isError || !data) return <ErrorState message="Test case not found." onRetry={refetch} />;

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-xl font-semibold">{data.scenarioTitle}</h1>
          <p className="text-sm text-muted-foreground">
            {data.module} · {data.variantType} variant
          </p>
        </div>
        <StatusPill status={data.status} />
      </div>

      {data.status === "failed" && data.errorSummary && (
        <Card className="border-critical/40 bg-critical/5">
          <CardContent>
            <p className="text-sm font-medium text-critical">Why it failed</p>
            <p className="mt-1 text-sm">{data.errorSummary}</p>
          </CardContent>
        </Card>
      )}

      {(data.status === "inconclusive" || data.status === "not_executed") && data.errorSummary && (
        <Card className={data.status === "inconclusive" ? "border-warning/40 bg-warning/5" : "border-border bg-muted/40"}>
          <CardContent>
            <p className="text-sm font-medium">{data.status === "inconclusive" ? "Why it is inconclusive" : "Why it was not executed"}</p>
            <p className="mt-1 text-sm text-muted-foreground">{data.errorSummary}</p>
          </CardContent>
        </Card>
      )}

      {data.healed && (
        <Card className="border-primary/40 bg-primary/5">
          <CardContent className="flex items-center gap-2 text-sm">
            <Wand2 className="size-4 text-primary" />
            <span>This test was auto-healed and re-verified against the real suite before being marked passing.</span>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <CardTitle className="text-sm font-medium text-muted-foreground">Generated spec</CardTitle>
        </CardHeader>
        <CardContent>
          <pre className="overflow-x-auto rounded-lg bg-muted p-4 font-mono text-xs leading-relaxed">
            {data.specPreview ??
              `test("${data.scenarioTitle}", async ({ page }) => {\n  // generated by ScriptGenerationAgent\n});`}
          </pre>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-sm font-medium text-muted-foreground">Run history</CardTitle>
        </CardHeader>
        <CardContent className="flex items-center gap-3 text-sm text-muted-foreground">
          <Clock className="size-4" />
          Last run took {(data.durationMs / 1000).toFixed(1)}s
        </CardContent>
      </Card>
    </div>
  );
}
