"""
indexer.py — build the knowledge graph and code chunks for one checkout.

    idx = index_repository(root, all_paths=tree_paths)

1. per-file parsers: python_parser (stdlib ast), js_parser (JS/TS/HTML/Vue/Svelte patterns), generic_parser
   (Java, Kotlin, Go, Rust, Ruby, PHP, C#, Swift, Dart, C/C++ … — declaration-aligned chunks, symbols, routes,
   tests), plus docs, stylesheets, manifests and config;
2. linker: resolve call names → symbol edges, frontend API calls → route edges (`calls_api`, `submits_to`),
   route/form handler names → handler symbols, tests → the symbols / modules they exercise, client-side pages →
   the components they render;
3. repo_model: counts, routes, build plan, risk signals and **coverage** (what was indexed, by language, and what
   was skipped and why — traceability's absence protocol refuses `not_implemented` when coverage is incomplete).

Which files are eligible (skip-dirs, size limit, extensions, file cap) is defined once in engines/repo_intel/files.py
and shared with the fetcher (tools/agent_eval/repo_scan.py).
"""

import json
import os
import posixpath
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

from engines.repo_intel import INDEXER_VERSION
from engines.repo_intel.files import (
    DOC_EXT,
    MAX_FILE_BYTES,
    MAX_FILES,
    NAMED_TEXT_FILES,
    SOURCE_EXT,
    TEXT_EXT,
    ext_of,
    is_skipped,
    language_of,
)
from engines.repo_intel.generic_parser import family_of, parse_generic, span_chunks
from engines.repo_intel.js_parser import parse_js
from engines.repo_intel.model import Chunk, Graph, Node, normalize_route_path
from engines.repo_intel.python_parser import _window_chunks, parse_python

_JS_EXT = {".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs", ".mts", ".cts", ".vue", ".svelte", ".astro", ".html", ".htm"}
_STYLE_EXT = {".css", ".scss", ".sass", ".less"}
_DOC_EXT = set(DOC_EXT)
_TEXT_EXT = set(TEXT_EXT)
_UNSCANNED_SAMPLE = 400  # paths kept per coverage list (the counts are exact)


@dataclass
class RepoIndex:
    graph: Graph
    chunks: List[Chunk]
    repo_model: Dict
    indexer_version: str = INDEXER_VERSION
    languages: Dict[str, int] = field(default_factory=dict)
    file_count: int = 0

    @property
    def coverage(self) -> Dict:
        return self.repo_model.get("coverage") or {}


def _skipped(rel: str) -> bool:
    return is_skipped(rel)


def _is_generated(rel: str, text: str) -> bool:
    head = text[:600].lower()
    return rel.endswith((".min.js", ".min.css", ".map", "-lock.json", ".lock")) or "@generated" in head \
        or "do not edit" in head or "autogenerated" in head


def _walk(root: Path) -> List[str]:
    """Files under root, pruning vendored/build/hidden directories while walking (never descends node_modules)."""
    out: List[str] = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if not is_skipped(f"{d}/x"))
        rel_dir = Path(dirpath).relative_to(root).as_posix()
        for name in filenames:
            out.append(name if rel_dir == "." else f"{rel_dir}/{name}")
    return sorted(out)


def index_repository(root: Path, all_paths: Optional[List[str]] = None, max_files: int = MAX_FILES) -> RepoIndex:
    root = root.resolve()
    on_disk_list = _walk(root)
    on_disk = set(on_disk_list)
    listed = sorted(p for p in set(all_paths or []) | on_disk if not is_skipped(p))
    g = Graph()
    chunks: List[Chunk] = []
    calls: Dict[str, Set[str]] = {}
    refs: Dict[str, Set[str]] = {}
    api_calls: List[Tuple[str, str, str]] = []
    languages: Dict[str, int] = {}
    deps: List[str] = []
    indexed_by_lang: Dict[str, int] = {}
    skipped: Dict[str, int] = {}
    unfetched_source: List[str] = []
    unindexed_source: List[str] = []
    parsed = 0

    def skip(rel: str, reason: str) -> None:
        skipped[reason] = skipped.get(reason, 0) + 1
        if ext_of(rel) in SOURCE_EXT:
            target = unfetched_source if reason == "not_fetched" else unindexed_source
            target.append(rel)

    for rel in listed:
        ext = ext_of(rel)
        name = rel.rsplit("/", 1)[-1]
        lang = language_of(rel)
        if lang:
            languages[lang] = languages.get(lang, 0) + 1
        if rel not in on_disk:  # listed but not fetched: keep it visible in the graph
            g.add(Node("file", f"file:{rel}", rel, name=name, props={"fetched": False}))
            skip(rel, "not_fetched")
            continue
        path = root / rel
        if ext not in _TEXT_EXT and name.lower() not in NAMED_TEXT_FILES:
            skip(rel, "unsupported_type")
            continue
        try:
            size = path.stat().st_size
        except OSError:
            skip(rel, "unreadable")
            continue
        if size > MAX_FILE_BYTES:
            g.add(Node("file", f"file:{rel}", rel, name=name, props={"fetched": True, "too_large": True}))
            skip(rel, "too_large")
            continue
        if parsed >= max_files:
            skip(rel, "file_cap")
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            skip(rel, "unreadable")
            continue
        if "\x00" in text[:2000]:
            skip(rel, "binary")
            continue
        if _is_generated(rel, text):
            skip(rel, "generated")
            continue
        parsed += 1
        indexed_by_lang[lang or ("Docs" if ext in _DOC_EXT else "Config")] = \
            indexed_by_lang.get(lang or ("Docs" if ext in _DOC_EXT else "Config"), 0) + 1

        if ext in (".py", ".pyi"):
            c, cl, rf, _imports = parse_python(rel, text, g)
            chunks += c
            calls.update(cl)
            refs.update(rf)
        elif ext in _JS_EXT:
            c, ac = parse_js(rel, text, g)
            chunks += c
            api_calls += ac
        elif ext in _DOC_EXT:
            g.add(Node("file", f"file:{rel}", rel, 1, text.count("\n") + 1, name, {"lang": "doc"}))
            chunks += _doc_chunks(rel, text, g)
        elif family_of(rel):
            c, cl = parse_generic(rel, text, g)
            chunks += c
            calls.update(cl)
        elif ext in _STYLE_EXT or ext in SOURCE_EXT:  # stylesheets, SQL, Prisma, shell without a family …
            c, _ = parse_generic(rel, text, g)
            chunks += c or span_chunks(rel, text.splitlines(), [], {})
        else:
            g.add(Node("file", f"file:{rel}", rel, 1, text.count("\n") + 1, name, {"lang": ext.lstrip(".") or name}))
            chunks += _window_chunks(rel, text, size=60, overlap=0)
            deps += _deps_from_manifest(rel, text, g)
            _env_from_example(rel, text, g)
        if name == "requirements.txt":  # parsed as a doc above; its dependencies still count
            deps += _deps_from_manifest(rel, text, g)

    _link_calls(g, calls, refs)
    _link_handlers(g)
    _link_api_calls(g, api_calls)
    _link_tests(g, calls)
    _link_js_tests(g, on_disk)
    _link_pages(g, on_disk)
    coverage = {
        "files_listed": len(listed),
        "files_on_disk": len([p for p in on_disk_list if not is_skipped(p)]),
        "files_indexed": parsed,
        "by_language": dict(sorted(indexed_by_lang.items(), key=lambda kv: -kv[1])),
        "skipped": dict(sorted(skipped.items())),
        "unfetched_source_count": len(unfetched_source),
        "unindexed_source_count": len(unindexed_source),
        "unfetched_source": unfetched_source[:_UNSCANNED_SAMPLE],
        "unindexed_source": unindexed_source[:_UNSCANNED_SAMPLE],
        "file_cap": max_files,
        "complete": not unfetched_source and not unindexed_source,
    }
    model = _repo_model(g, listed, languages, deps, root)
    model["coverage"] = coverage
    return RepoIndex(g, chunks, model, INDEXER_VERSION, languages, len(listed))


# ── docs / manifests ─────────────────────────────────────────────────────────

def _doc_chunks(rel: str, text: str, g: Graph) -> List[Chunk]:
    lines = text.splitlines()
    heads = [i for i, l in enumerate(lines) if re.match(r"^#{1,4}\s+\S", l)] or [0]
    if heads[0] != 0:
        heads = [0] + heads
    out = []
    for a, b in zip(heads, heads[1:] + [len(lines)]):
        body = "\n".join(lines[a:b]).strip()
        if not body:
            continue
        title = lines[a].lstrip("#").strip()[:120] if lines[a].startswith("#") else rel
        key = f"doc_section:{rel}:{a + 1}"
        g.add(Node("doc_section", key, rel, a + 1, b, title))
        g.link(f"file:{rel}", "defines", key)
        for s in range(a, b, 80):
            out.append(Chunk(rel, s + 1, min(b, s + 80), "\n".join(lines[s:min(b, s + 80)]), title))
    return out


def _deps_from_manifest(rel: str, text: str, g: Graph) -> List[str]:
    name = rel.rsplit("/", 1)[-1]
    found: List[str] = []
    if name == "requirements.txt":
        for line in text.splitlines():
            m = re.match(r"\s*([A-Za-z0-9_.\-]+)(\[[^\]]*\])?\s*([<>=!~].*)?$", line.split("#")[0])
            if m and m.group(1):
                found.append(m.group(1).lower())
    elif name == "package.json":
        try:
            data = json.loads(text)
            found = list((data.get("dependencies") or {}).keys()) + list((data.get("devDependencies") or {}).keys())
        except ValueError:
            pass
    elif name == "pyproject.toml":
        found = [m.group(1).lower() for m in re.finditer(r'^\s*"([A-Za-z0-9_.\-]+)[^"]*",?\s*$', text, re.M)]
    for d in found:
        g.add(Node("dependency", f"dependency:{d}", name=d))
        g.link(f"file:{rel}", "imports", f"dependency:{d}")
    return found


def _env_from_example(rel: str, text: str, g: Graph) -> None:
    """Variables declared in .env.example / .env.sample / .env.template (committed .env files are a review finding)."""
    if ext_of(rel) != ".env.example":
        return
    for m in re.finditer(r"^\s*(?:export\s+)?([A-Z][A-Z0-9_]+)\s*=", text, re.M):
        g.add(Node("config", f"config:{m.group(1)}", name=m.group(1), props={"declared_in": rel}))
        g.link(f"file:{rel}", "defines", f"config:{m.group(1)}")


# ── linking ──────────────────────────────────────────────────────────────────

def _symbols_by_name(g: Graph) -> Dict[str, List[str]]:
    by_name: Dict[str, List[str]] = {}
    for n in g.of_kind("symbol"):
        by_name.setdefault((n.name or "").split(".")[-1], []).append(n.key)
    return by_name


def _link_calls(g: Graph, calls: Dict[str, Set[str]], refs: Dict[str, Set[str]]) -> None:
    by_name = _symbols_by_name(g)
    prompts_by_name = {n.name: n.key for n in g.of_kind("prompt")}
    for src, names in calls.items():
        for name in names:
            targets = by_name.get(name, [])
            if 0 < len(targets) <= 3:  # ambiguous common names (get, run) would add noise
                for t in targets:
                    g.link(src, "calls", t)
    for src, names in refs.items():
        for name in names & prompts_by_name.keys():
            g.link(src, "uses_prompt", prompts_by_name[name])


def _resolve_name(by_name: Dict[str, List[str]], name: str, near: Optional[str]) -> List[str]:
    """Symbols called `name`: the one in the same file if there is one, else up to 3 unambiguous candidates."""
    targets = by_name.get(name, [])
    same = [t for t in targets if near and t.startswith(f"symbol:{near}#")]
    if same:
        return same[:1]
    return targets if 0 < len(targets) <= 3 else []


def _link_handlers(g: Graph) -> None:
    """Routes / forms registered by handler *name* in another file (Django urls.py, add_url_rule, Go mux, Laravel …)."""
    by_name = _symbols_by_name(g)
    for r in g.of_kind("route"):
        name = r.props.get("handler_name")
        if name and not r.props.get("handler"):
            for t in _resolve_name(by_name, name, r.file_path):
                g.link(r.key, "exposes", t)
                r.props.setdefault("handler", t)
    for f in g.of_kind("form"):
        for name in f.props.get("handler_names") or []:
            for t in _resolve_name(by_name, name, f.file_path):
                g.link(f.key, "submits_to", t)


def _link_api_calls(g: Graph, api_calls: List[Tuple[str, str, str]]) -> None:
    routes = [(n.props.get("method", "GET"), normalize_route_path(n.props.get("path", "")), n.key) for n in g.of_kind("route")]
    for owner, method, url in api_calls:
        path = re.sub(r"^https?://[^/]+", "", url)
        path = re.sub(r"^\$\{[^}]*\}", "", path)  # `${API_BASE}/api/x`
        if not path.startswith("/"):
            continue
        want = normalize_route_path(path)
        for m, rp, key in routes:
            if _path_match(want, rp) and m in (method, "ANY"):
                g.link(owner, "submits_to" if owner.startswith("form:") else "calls_api", key)
                break
        else:
            for m, rp, key in routes:  # method unknown in the source (fetch with a variable options object)
                if _path_match(want, rp):
                    g.link(owner, "submits_to" if owner.startswith("form:") else "calls_api", key)
                    break


def _path_match(a: str, b: str) -> bool:
    pa, pb = a.strip("/").split("/"), b.strip("/").split("/")
    if len(pa) != len(pb):
        return False
    return all(x == y or "*" in (x, y) for x, y in zip(pa, pb))


def _link_tests(g: Graph, calls: Dict[str, Set[str]]) -> None:
    by_name: Dict[str, List[str]] = {}
    for n in g.of_kind("symbol"):
        if not n.key.startswith("symbol:") or "/test" in f"/{n.file_path}":
            continue
        by_name.setdefault((n.name or "").split(".")[-1], []).append(n.key)
    for t in g.of_kind("test"):
        sym = next((d for k, d in g.out(t.key, ["defines"])), None)
        for name in calls.get(sym, set()):
            for target in by_name.get(name, [])[:3]:
                g.link(t.key, "tests", target)


_JS_RESOLVE = ("", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".vue", ".svelte", "/index.ts", "/index.tsx", "/index.js",
               "/index.jsx")


def _resolve_module(base_file: str, spec: str, on_disk: Set[str]) -> Optional[str]:
    if spec.startswith(("@/", "~/")):
        candidates = [f"src/{spec[2:]}", spec[2:]]
    else:
        candidates = [posixpath.normpath(posixpath.join(posixpath.dirname(base_file), spec))]
    for c in candidates:
        for suffix in _JS_RESOLVE:
            if c + suffix in on_disk:
                return c + suffix
    return None


def _link_js_tests(g: Graph, on_disk: Set[str]) -> None:
    """A JS/TS test exercises the modules it imports: test --tests--> file:<module>."""
    for t in g.of_kind("test"):
        for spec in t.props.get("imports") or []:
            target = _resolve_module(t.file_path or "", spec, on_disk)
            if target and f"file:{target}" in g.nodes:
                g.link(t.key, "tests", f"file:{target}")


def _link_pages(g: Graph, on_disk: Set[str]) -> None:
    """Client-side routes render their component; an index.html entry renders its module script."""
    components: Dict[str, List[str]] = {}
    for c in g.of_kind("component"):
        components.setdefault(c.name or "", []).append(c.key)
    for p in g.of_kind("page"):
        comp = p.props.get("component")
        for key in components.get(comp or "", [])[:2]:
            g.link(p.key, "renders", key)
            g.link(p.key, "renders", f"file:{g.nodes[key].file_path}")
        script = p.props.get("entry_script")
        if script:
            base = posixpath.dirname(p.file_path or "")
            for cand in (script, posixpath.normpath(posixpath.join(base, script))):
                if cand in on_disk and f"file:{cand}" in g.nodes:
                    g.link(p.key, "renders", f"file:{cand}")
                    break


# ── repo model ───────────────────────────────────────────────────────────────

_TEST_PATH = re.compile(r"(^|/)(tests?|__tests__|spec|e2e|cypress)(/|$)|(_test|\.test|\.spec|_spec|Test|Tests)\.\w+$|(^|/)test_[^/]*$")


def has_tests(g: Graph, files: List[str]) -> bool:
    """Automated tests exist: test nodes in the index, or test files in the repository listing."""
    return bool(g.of_kind("test")) or any(_TEST_PATH.search(f) and ext_of(f) in SOURCE_EXT for f in files)


def _repo_model(g: Graph, files: List[str], languages: Dict[str, int], deps: List[str], root: Path) -> Dict:
    kinds: Dict[str, int] = {}
    for n in g.nodes.values():
        kinds[n.kind] = kinds.get(n.kind, 0) + 1
    names = {f.rsplit("/", 1)[-1].lower() for f in files}
    build = _build_plan(files, deps, g)
    risks = []
    if not has_tests(g, files):
        risks.append("No automated tests found")
    if kinds.get("route") and not any(re.search(r"health|status|ping|ready", n.key) for n in g.of_kind("route")):
        risks.append("No health-check route")
    if "dockerfile" not in names:
        risks.append("No Dockerfile")
    return {
        "counts": kinds,
        "languages": languages,
        "routes": sorted({n.name for n in g.of_kind("route")})[:200],
        "pages": sorted({n.name for n in g.of_kind("page")})[:100],
        "llm_calls": kinds.get("model_call", 0),
        "models": sorted({str(n.props.get("model")) for n in g.of_kind("model_call") + g.of_kind("agent")
                          if n.props.get("model")}),
        "env_vars": sorted({n.name for n in g.of_kind("config")})[:100],
        "dependencies": sorted(set(deps))[:300],
        "build_plan": build,
        "risk_signals": risks,
    }


def _build_plan(files: List[str], deps: List[str], g: Graph) -> Dict:
    """One entry per runnable component (a repo is often a Python API + a JS frontend)."""
    components: List[Dict] = []
    dockerfiles = [f for f in files if f.rsplit("/", 1)[-1].lower() == "dockerfile"]
    compose = [f for f in files if f.rsplit("/", 1)[-1].lower() in ("docker-compose.yml", "docker-compose.yaml", "compose.yaml")]
    for f in files:
        name, folder = f.rsplit("/", 1)[-1], (f.rsplit("/", 1)[0] if "/" in f else ".")
        if name == "package.json" and "node_modules" not in f:
            components.append({"kind": "node", "dir": folder, "install": "npm ci", "start": "npm run build && npm start"})
        elif name in ("requirements.txt", "pyproject.toml") and not any(c["dir"] == folder and c["kind"] == "python" for c in components):
            server = ("uvicorn" if {"uvicorn", "fastapi"} & set(deps) else "streamlit" if "streamlit" in deps
                      else "flask" if "flask" in deps else "gradio" if "gradio" in deps else None)
            components.append({"kind": "python", "dir": folder, "install": f"pip install -r {f}" if name == "requirements.txt"
                               else "pip install .", "server": server})
    return {
        "strategy": "compose" if compose else "docker" if dockerfiles else "detected" if components else "unknown",
        "compose_files": compose, "dockerfiles": dockerfiles, "components": components,
        "required_env": sorted({n.name for n in g.of_kind("config")})[:50],
    }
