import type { Project, Run, Scenario, TestCase, Recommendation } from "./types";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj_checkout",
    name: "acme/checkout-agent",
    githubUrl: "https://github.com/acme/checkout-agent",
    branch: "main",
    lastRunStatus: "completed",
    lastQualityScore: 86,
    updatedAt: "2026-09-23T14:12:00Z",
    mode: "brd_and_live",
    liveUrl: null,
    brdPath: null,
    isSample: true,
    hasLiveAuth: false,
  },
  {
    id: "proj_support",
    name: "acme/support-bot",
    githubUrl: "https://github.com/acme/support-bot",
    branch: "main",
    lastRunStatus: "completed",
    lastQualityScore: 71,
    updatedAt: "2026-09-22T09:40:00Z",
    mode: "brd_and_live",
    liveUrl: null,
    brdPath: null,
    isSample: true,
    hasLiveAuth: false,
  },
  {
    id: "proj_docs",
    name: "acme/docs-compliance-agent",
    githubUrl: "https://github.com/acme/docs-compliance-agent",
    branch: "develop",
    lastRunStatus: "completed",
    lastQualityScore: 78,
    updatedAt: "2026-09-24T08:07:38Z",
    mode: "brd_and_live",
    liveUrl: null,
    brdPath: null,
    isSample: true,
    hasLiveAuth: false,
  },
];

export const MOCK_RUNS: Run[] = [
  {
    id: "run_128",
    projectId: "proj_checkout",
    projectName: "acme/checkout-agent",
    status: "completed",
    currentStage: "reporting",
    startedAt: "2026-09-23T14:08:00Z",
    finishedAt: "2026-09-23T14:12:00Z",
    durationSec: 134,
    stats: {
      scenariosFound: 24,
      testCasesGenerated: 142,
      passed: 134,
      failed: 5,
      healed: 17,
      skipped: 3,
      coveragePct: 73,
      qualityScore: 86,
      riskLevel: "medium",
      criticalDefects: 3,
      duplicatesRejected: 8,
    },
    qualityBreakdown: [
      { label: "Test Coverage", score: 30, max: 35 },
      { label: "Pass Rate", score: 25, max: 25 },
      { label: "Reliability", score: 17, max: 20 },
      { label: "Security Validation", score: 18, max: 20 },
    ],
    trend: [40, 55, 50, 70, 65, 80, 86],
    // Legacy Playwright runs: not agent evaluations
    mode: null,
    liveUrl: null,
    githubUrl: "",
    projectIsSample: true,
    commitRef: null,
    brdSource: null,
    summary: null,
    errorMessage: null,
    compliance: null,
    heartbeatAt: null,
    cancelRequested: false,
  },
  {
    id: "run_129",
    projectId: "proj_docs",
    projectName: "acme/docs-compliance-agent",
    // Samples are always finished runs: nothing polls a sample, so an "in flight" sample would never end.
    status: "completed",
    currentStage: "reporting",
    startedAt: "2026-09-24T08:05:00Z",
    finishedAt: "2026-09-24T08:07:38Z",
    durationSec: 158,
    stats: {
      scenariosFound: 24,
      testCasesGenerated: 142,
      passed: 121,
      failed: 9,
      healed: 6,
      skipped: 12,
      coveragePct: 66,
      qualityScore: 78,
      riskLevel: "medium",
      criticalDefects: 2,
      duplicatesRejected: 5,
    },
    qualityBreakdown: [
      { label: "Test Coverage", score: 27, max: 35 },
      { label: "Pass Rate", score: 22, max: 25 },
      { label: "Reliability", score: 15, max: 20 },
      { label: "Security Validation", score: 14, max: 20 },
    ],
    trend: [60, 64, 71, 69, 74, 78],
    // Legacy Playwright runs: not agent evaluations
    mode: null,
    liveUrl: null,
    githubUrl: "",
    projectIsSample: true,
    commitRef: null,
    brdSource: null,
    summary: null,
    errorMessage: null,
    compliance: null,
    heartbeatAt: null,
    cancelRequested: false,
  },
  {
    id: "run_101",
    projectId: "proj_support",
    projectName: "acme/support-bot",
    status: "completed",
    currentStage: "reporting",
    startedAt: "2026-09-22T09:36:00Z",
    finishedAt: "2026-09-22T09:40:00Z",
    durationSec: 96,
    stats: {
      scenariosFound: 18,
      testCasesGenerated: 88,
      passed: 79,
      failed: 4,
      healed: 5,
      skipped: 0,
      coveragePct: 58,
      qualityScore: 71,
      riskLevel: "medium",
      criticalDefects: 1,
      duplicatesRejected: 3,
    },
    qualityBreakdown: [
      { label: "Test Coverage", score: 22, max: 35 },
      { label: "Pass Rate", score: 20, max: 25 },
      { label: "Reliability", score: 16, max: 20 },
      { label: "Security Validation", score: 13, max: 20 },
    ],
    trend: [50, 48, 60, 55, 62, 68, 71],
    // Legacy Playwright runs: not agent evaluations
    mode: null,
    liveUrl: null,
    githubUrl: "",
    projectIsSample: true,
    commitRef: null,
    brdSource: null,
    summary: null,
    errorMessage: null,
    compliance: null,
    heartbeatAt: null,
    cancelRequested: false,
  },
];

export const PIPELINE_STAGES = [
  "discovery",
  "testdata",
  "semantic_map",
  "script_generation",
  "ui_execution",
  "healing",
  "reporting",
] as const;

export const MOCK_SCENARIOS: Scenario[] = [
  { id: "sc_1", runId: "run_128", title: "User can log in with valid credentials", module: "Auth", confidence: 0.94 },
  { id: "sc_2", runId: "run_128", title: "User can reset a forgotten password", module: "Auth", confidence: 0.88 },
  { id: "sc_3", runId: "run_128", title: "User can complete checkout with a saved card", module: "Checkout", confidence: 0.91 },
  { id: "sc_4", runId: "run_128", title: "Checkout rejects an expired payment token", module: "Checkout", confidence: 0.62 },
  { id: "sc_5", runId: "run_128", title: "Search returns relevant results for partial queries", module: "Search", confidence: 0.9 },
];

export const MOCK_TEST_CASES: TestCase[] = [
  { id: "tc_1", runId: "run_128", scenarioTitle: "Login with valid credentials", module: "Auth", variantType: "positive", status: "passed", durationMs: 1240, healed: false },
  { id: "tc_2", runId: "run_128", scenarioTitle: "Reject empty password field", module: "Auth", variantType: "negative", status: "passed", durationMs: 980, healed: false },
  { id: "tc_3", runId: "run_128", scenarioTitle: "Checkout with expired session", module: "Checkout", variantType: "boundary", status: "healed", durationMs: 2110, healed: true },
  {
    id: "tc_4",
    runId: "run_128",
    scenarioTitle: "SQL-injection payload in search box",
    module: "Search",
    variantType: "sql_injection",
    status: "failed",
    durationMs: 1560,
    healed: false,
    errorSummary: "Expected sanitized results, got raw query reflected in response — looks like a real defect, not a flaky test.",
    specPreview: `test("search rejects sql-injection payload", async ({ page }) => {\n  await page.goto("/search");\n  await page.getByRole("searchbox").fill("' OR 1=1 --");\n  await page.getByRole("button", { name: "Search" }).click();\n  await expect(page.getByTestId("results-list")).not.toContainText("OR 1=1");\n});`,
  },
  { id: "tc_5", runId: "run_128", scenarioTitle: "Admin panel — disable a user account", module: "Admin", variantType: "positive", status: "skipped", durationMs: 0, healed: false },
];

export const MOCK_RECOMMENDATIONS: Recommendation[] = [
  {
    id: "rec_1",
    runId: "run_128",
    category: "missing_negative_case",
    severity: "critical",
    summary: "Checkout module has no negative test for an expired payment token.",
    evidenceRef: "tc_3",
    evidenceType: "test_case",
  },
  {
    id: "rec_2",
    runId: "run_128",
    category: "coverage_gap",
    severity: "warning",
    summary: "Admin panel coverage is at 40% — 6 fields are untested.",
    evidenceRef: "sc_5",
    evidenceType: "scenario",
  },
  {
    id: "rec_3",
    runId: "run_128",
    category: "flaky_behavior",
    severity: "info",
    summary: "\"Search suggestions\" needed healing twice across the last 5 runs.",
    evidenceRef: "tc_4",
    evidenceType: "test_case",
  },
];
